const std = @import("std");

pub fn build(b: *std.Build) !void {
    const picolibc_ver = try std.SemanticVersion.parse("1.8.6");
    const newlib_ver = try std.SemanticVersion.parse("4.3.0");

    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const reent_h = b.addConfigHeader(.{
        .include_path = "reent.h",
        .style = .blank,
    }, .{});
    const picolibc_h = b.addConfigHeader(.{
        .include_path = "picolibc.h",
        .style = .{
            .cmake = b.path("picolibc.h.in"),
        },
    }, .{
        .ATOMIC_UNGETC = {},
        .FAST_STRCMP = {},
        .MISSING_SYSCALL_NAMES = null,
        .NEWLIB_GLOBAL_ERRNO = null,
        .__PICOLIBC_ERRNO_FUNCTION = null,
        .NEWLIB_TLS = {},
        .PICOLIBC_TLS = {},
        .POSIX_IO = {},
        .POSIX_CONSOLE = {},
        .PREFER_SIZE_OVER_SPEED = {},
        .REENTRANT_SYSCALLS_PROVIDED = {},
        .TINY_STDIO = {},
        ._ATEXIT_DYNAMIC_ALLOC = {},
        ._FSEEK_OPTIMIZATION = {},
        ._FVWRITE_IN_STREAMIO = {},
        ._HAVE_ALIAS_ATTRIBUTE = {},
        ._HAVE_ALLOC_SIZE = {},
        ._HAVE_ATTRIBUTE_ALWAYS_INLINE = {},
        ._HAVE_ATTRIBUTE_GNU_INLINE = {},
        ._HAVE_BITFIELDS_IN_PACKED_STRUCTS = {},
        ._HAVE_BUILTIN_ALLOCA = {},
        ._HAVE_BUILTIN_COPYSIGN = {},
        ._HAVE_BUILTIN_COPYSIGNL = {},
        ._HAVE_BUILTIN_CTZ = {},
        ._HAVE_BUILTIN_CTZL = {},
        ._HAVE_BUILTIN_CTZLL = {},
        ._HAVE_BUILTIN_EXPECT = {},
        ._HAVE_BUILTIN_FFS = {},
        ._HAVE_BUILTIN_FFSL = {},
        ._HAVE_BUILTIN_FFSLL = {},
        ._HAVE_BUILTIN_FINITEL = {},
        ._HAVE_BUILTIN_ISFINITE = {},
        ._HAVE_BUILTIN_ISINF = {},
        ._HAVE_BUILTIN_ISINFL = {},
        ._HAVE_BUILTIN_ISNAN = {},
        ._HAVE_BUILTIN_ISNANL = {},
        ._HAVE_BUILTIN_MUL_OVERFLOW = {},
        ._HAVE_BUILTIN_ADD_OVERFLOW = {},
        ._HAVE_CC_INHIBIT_LOOP_TO_LIBCALL = {},
        ._HAVE_COMPLEX = {},
        ._HAVE_BUILTIN_COMPLEX = {},
        ._HAVE_FCNTL = {},
        ._HAVE_FORMAT_ATTRIBUTE = {},
        ._HAVE_IEEEFP_FUNCS = {},
        ._HAVE_INITFINI_ARRAY = {},
        ._HAVE_INIT_FINI = {},
        ._HAVE_LONG_DOUBLE = {},
        ._HAVE_NO_BUILTIN_ATTRIBUTE = {},
        ._HAVE_PICOLIBC_TLS_API = {},
        ._HAVE_SEMIHOST = {},
        ._HAVE_WEAK_ATTRIBUTE = {},
        ._ICONV_ENABLE_EXTERNAL_CCS = {},
        ._ICONV_FROM_ENCODING_ = {},
        ._ICONV_FROM_ENCODING_BIG5 = {},
        ._ICONV_FROM_ENCODING_CP775 = {},
        ._ICONV_FROM_ENCODING_CP850 = {},
        ._ICONV_FROM_ENCODING_CP852 = {},
        ._ICONV_FROM_ENCODING_CP855 = {},
        ._ICONV_FROM_ENCODING_CP866 = {},
        ._ICONV_FROM_ENCODING_EUC_JP = {},
        ._ICONV_FROM_ENCODING_EUC_KR = {},
        ._ICONV_FROM_ENCODING_EUC_TW = {},
        ._ICONV_FROM_ENCODING_ISO_8859_1 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_10 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_11 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_13 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_14 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_15 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_2 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_3 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_4 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_5 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_6 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_7 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_8 = {},
        ._ICONV_FROM_ENCODING_ISO_8859_9 = {},
        ._ICONV_FROM_ENCODING_ISO_IR_111 = {},
        ._ICONV_FROM_ENCODING_KOI8_R = {},
        ._ICONV_FROM_ENCODING_KOI8_RU = {},
        ._ICONV_FROM_ENCODING_KOI8_U = {},
        ._ICONV_FROM_ENCODING_KOI8_UNI = {},
        ._ICONV_FROM_ENCODING_UCS_2 = {},
        ._ICONV_FROM_ENCODING_UCS_2BE = {},
        ._ICONV_FROM_ENCODING_UCS_2LE = {},
        ._ICONV_FROM_ENCODING_UCS_2_INTERNAL = {},
        ._ICONV_FROM_ENCODING_UCS_4 = {},
        ._ICONV_FROM_ENCODING_UCS_4BE = {},
        ._ICONV_FROM_ENCODING_UCS_4LE = {},
        ._ICONV_FROM_ENCODING_UCS_4_INTERNAL = {},
        ._ICONV_FROM_ENCODING_US_ASCII = {},
        ._ICONV_FROM_ENCODING_UTF_16 = {},
        ._ICONV_FROM_ENCODING_UTF_16BE = {},
        ._ICONV_FROM_ENCODING_UTF_16LE = {},
        ._ICONV_FROM_ENCODING_UTF_8 = {},
        ._ICONV_FROM_ENCODING_WIN_1250 = {},
        ._ICONV_FROM_ENCODING_WIN_1251 = {},
        ._ICONV_FROM_ENCODING_WIN_1252 = {},
        ._ICONV_FROM_ENCODING_WIN_1253 = {},
        ._ICONV_FROM_ENCODING_WIN_1254 = {},
        ._ICONV_FROM_ENCODING_WIN_1255 = {},
        ._ICONV_FROM_ENCODING_WIN_1256 = {},
        ._ICONV_FROM_ENCODING_WIN_1257 = {},
        ._ICONV_FROM_ENCODING_WIN_1258 = {},
        ._ICONV_TO_ENCODING_ = {},
        ._ICONV_TO_ENCODING_BIG5 = {},
        ._ICONV_TO_ENCODING_CP775 = {},
        ._ICONV_TO_ENCODING_CP850 = {},
        ._ICONV_TO_ENCODING_CP852 = {},
        ._ICONV_TO_ENCODING_CP855 = {},
        ._ICONV_TO_ENCODING_CP866 = {},
        ._ICONV_TO_ENCODING_EUC_JP = {},
        ._ICONV_TO_ENCODING_EUC_KR = {},
        ._ICONV_TO_ENCODING_EUC_TW = {},
        ._ICONV_TO_ENCODING_ISO_8859_1 = {},
        ._ICONV_TO_ENCODING_ISO_8859_10 = {},
        ._ICONV_TO_ENCODING_ISO_8859_11 = {},
        ._ICONV_TO_ENCODING_ISO_8859_13 = {},
        ._ICONV_TO_ENCODING_ISO_8859_14 = {},
        ._ICONV_TO_ENCODING_ISO_8859_15 = {},
        ._ICONV_TO_ENCODING_ISO_8859_2 = {},
        ._ICONV_TO_ENCODING_ISO_8859_3 = {},
        ._ICONV_TO_ENCODING_ISO_8859_4 = {},
        ._ICONV_TO_ENCODING_ISO_8859_5 = {},
        ._ICONV_TO_ENCODING_ISO_8859_6 = {},
        ._ICONV_TO_ENCODING_ISO_8859_7 = {},
        ._ICONV_TO_ENCODING_ISO_8859_8 = {},
        ._ICONV_TO_ENCODING_ISO_8859_9 = {},
        ._ICONV_TO_ENCODING_ISO_IR_111 = {},
        ._ICONV_TO_ENCODING_KOI8_R = {},
        ._ICONV_TO_ENCODING_KOI8_RU = {},
        ._ICONV_TO_ENCODING_KOI8_U = {},
        ._ICONV_TO_ENCODING_KOI8_UNI = {},
        ._ICONV_TO_ENCODING_UCS_2 = {},
        ._ICONV_TO_ENCODING_UCS_2BE = {},
        ._ICONV_TO_ENCODING_UCS_2LE = {},
        ._ICONV_TO_ENCODING_UCS_2_INTERNAL = {},
        ._ICONV_TO_ENCODING_UCS_4 = {},
        ._ICONV_TO_ENCODING_UCS_4BE = {},
        ._ICONV_TO_ENCODING_UCS_4LE = {},
        ._ICONV_TO_ENCODING_UCS_4_INTERNAL = {},
        ._ICONV_TO_ENCODING_US_ASCII = {},
        ._ICONV_TO_ENCODING_UTF_16 = {},
        ._ICONV_TO_ENCODING_UTF_16BE = {},
        ._ICONV_TO_ENCODING_UTF_16LE = {},
        ._ICONV_TO_ENCODING_UTF_8 = {},
        ._ICONV_TO_ENCODING_WIN_1250 = {},
        ._ICONV_TO_ENCODING_WIN_1251 = {},
        ._ICONV_TO_ENCODING_WIN_1252 = {},
        ._ICONV_TO_ENCODING_WIN_1253 = {},
        ._ICONV_TO_ENCODING_WIN_1254 = {},
        ._ICONV_TO_ENCODING_WIN_1255 = {},
        ._ICONV_TO_ENCODING_WIN_1256 = {},
        ._ICONV_TO_ENCODING_WIN_1257 = {},
        ._ICONV_TO_ENCODING_WIN_1258 = {},
        ._IEEE_LIBM = {},
        ._IO_FLOAT_EXACT = {},
        ._PRINTF_SMALL_ULTOA = {},
        ._LITE_EXIT = {},
        ._MB_CAPABLE = null,
        ._MB_LEN_MAX = 1,
        ._NANO_FORMATTED_IO = null,
        ._NANO_MALLOC = {},
        .NEWLIB_VERSION = b.fmt("{}.{}.{}", .{ newlib_ver.major, newlib_ver.minor, newlib_ver.patch }),
        ._PICO_EXIT = {},
        .PROJECT_VERSION_MINOR = @as(i64, @intCast(picolibc_ver.minor)),
        .PROJECT_VERSION = b.fmt("{}.{}.{}", .{ picolibc_ver.major, picolibc_ver.minor, picolibc_ver.patch }),
        .PROJECT_VERSION_MAJOR = @as(i64, @intCast(picolibc_ver.major)),
        ._REENT_GLOBAL_ATEXIT = null,
        ._RETARGETABLE_LOCKING = {},
        ._UNBUF_STREAM_OPT = {},
        ._WANT_IO_C99_FORMATS = {},
        ._WANT_IO_LONG_LONG = null,
        ._WANT_IO_LONG_DOUBLE = null,
        ._WANT_MINIMAL_IO_LONG_LONG = null,
        ._WANT_IO_POS_ARGS = null,
        ._FORMAT_DEFAULT_DOUBLE = null,
        ._FORMAT_DEFAULT_FLOAT = null,
        ._FORMAT_DEFAULT_LONG_LONG = null,
        ._FORMAT_DEFAULT_INTEGER = {},
        ._FORMAT_DEFAULT_MINIMAL = null,
        ._WANT_MATH_ERRNO = null,
        ._WANT_REENT_SMALL = null,
        ._WANT_REGISTER_FINI = null,
        ._WANT_USE_LONG_TIME_T = null,
        ._WIDE_ORIENT = null,
        ._ASSERT_VERBOSE = {},
        .__HAVE_LOCALE_INFO_EXTENDED__ = null,
        .__HAVE_LOCALE_INFO__ = null,
        .NEWLIB_MINOR = @as(i64, @intCast(newlib_ver.minor)),
        .NEWLIB_PATCH = @as(i64, @intCast(newlib_ver.patch)),
        .NEWLIB_MAJOR = @as(i64, @intCast(newlib_ver.major)),
        .__OBSOLETE_MATH_DOUBLE = 1,
        .__OBSOLETE_MATH_FLOAT = 1,
        .__PICOLIBC_CRT_RUNTIME_SIZE = 0,
        .PROJECT_VERSION_PATCH = @as(i64, @intCast(picolibc_ver.patch)),
        .__SINGLE_THREAD__ = @intFromBool(@import("builtin").single_threaded),
        ._XTENSA_HAVE_CONFIG_CORE_ISA_H = @intFromBool(target.result.cpu.arch == .xtensa),
    });



    const newlib = b.addStaticLibrary(.{
        .name = "c",
        .target = target,
        .optimize = optimize,
    });
    newlib.addConfigHeader(picolibc_h);
    newlib.addConfigHeader(reent_h);

    newlib.addSystemIncludePath(b.path("newlib/libc/include"));
    newlib.addSystemIncludePath(b.path("newlib/libm/common"));
    newlib.addSystemIncludePath(b.path("newlib/libc/stdio"));
    newlib.addSystemIncludePath(b.path("newlib/libc/stdio/sys"));
    newlib.defineCMacro("_LIBC", null);
    switch (newlib.rootModuleTarget().cpu.arch) {
        .avr => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/avr/setjmp.S"));
        },
        .arc => {
            newlib.addSystemIncludePath(b.path("newlib/libc/machine/arc"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memcmp-bs-norm.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memcpy-archs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memcpy-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memset-archs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memset-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strchr-bs-norm.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strchr-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strcmp-archs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strcpy-bs-arc600.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strcpy-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strlen-bs-norm.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strlen-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strncpy-bs.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arc/strncpy.S"));
        },
        .arm, .armeb => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/aeabi_memcpy-armv7a.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memset-arm.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/setjmp.S"));
            // TODO
            // switch (newlib.rootModuleTarget().cpu.model.toCpu(.arm)) {
            //     else => {},
            // }
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memcpy-armv7a.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memcpy-armv7m.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-arm-tiny.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv4.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv4t.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv6.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv6m.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv7.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp-armv7m.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strlen-armv7.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/picolib/machine/arm/read_tp.S"));
        },
        .thumb, .thumbeb => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/picolib/machine/arm/read_tp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memset-thumb.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strlen-thumb1-Os.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/memset-thumb2.S"));
            // newlib.addAssemblyFile(b.path("newlib/libc/machine/arm/strlen-thumb2-Os.S"));
        },
        .aarch64, .aarch64_be, .aarch64_32 => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memmove.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memrchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/rawmemchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/stpcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strchrnul.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strncmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strnlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/aarch64/strrchr.S"));
        },
        .m68k => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/m68k/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/m68k/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/m68k/setjmp.S"));
        },
        .mips, .mipsel => {
            newlib.addSystemIncludePath(b.path("newlib/libc/machine/mips"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/mips/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/mips/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/mips/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/mips/strcmp.S"));
        },
        .riscv32, .riscv64 => {
            newlib.addSystemIncludePath(b.path("newlib/libc/machine/riscv"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/riscv/memcpy-asm.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/riscv/memmove.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/riscv/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/riscv/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/riscv/strcmp.S"));
        },
        .sparc => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/sparc/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/picolib/machine/sparc/interrupt.S"));
        },
        .spu_2 => {
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/fiprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/fiscanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/fprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/fscanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/iprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/iscanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/printf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/scanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/siprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/siscanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/sniprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/snprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/sprintf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/spu-mcount.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/spu_timer_flih.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/sscanf.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/spu/stack_reg_va.S"));
        },
        .x86, .x86_64 => {
            if (newlib.rootModuleTarget().cpu.arch == .x86_64) {
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memcpy-64.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memset-64.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/setjmp-64.S"));
                newlib.addAssemblyFile(b.path("picocrt/machine/x86/crt0-64.S"));
            } else {
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memchr-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memcmp-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memcpy-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memmove-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memset-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/setjmp-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/strlen-32.S"));
                newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/strchr-32.S"));
                newlib.addAssemblyFile(b.path("picocrt/machine/x86/crt0-32.S"));

                // libm
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_atan2.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_atan2f.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_frexp.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_frexpf.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_ldexp.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_ldexpf.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_log.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_log10.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_log10f.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_logf.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_tan.S"));
                newlib.addAssemblyFile(b.path("newlib/libm/machine/x86/f_tanf.S"));
            }
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memmove.S"));

            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/strchr.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/x86/strlen.S"));
        },
        .xtensa => {
            newlib.addSystemIncludePath(b.path("newlib/libc/machine/xtensa"));
            newlib.addSystemIncludePath(b.path("newlib/libc/sys/xtensa/include/xtensa/config"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/memcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/memset.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/setjmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/strcmp.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/strcpy.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/strlen.S"));
            newlib.addAssemblyFile(b.path("newlib/libc/machine/xtensa/strncpy.S"));
        },
        else => {},
    }
    newlib.addCSourceFiles(.{
        .files = libc,
        .flags = cflags,
    });
    newlib.addCSourceFiles(.{
        .files = libm,
        .flags = cflags,
    });
    newlib.addCSourceFiles(.{
        .files = switch (newlib.rootModuleTarget().cpu.arch) {
            .thumb, .thumbeb, .arm, .armeb => &.{
                // "newlib/libc/machine/arm/aeabi_memset.c",
                // "newlib/libc/machine/arm/bzero.c",
                // "newlib/libc/machine/arm/memchr.c",
                // "newlib/libc/machine/arm/memcpy.c",
                // "newlib/libc/machine/arm/memmove.c",
                // "newlib/libc/machine/arm/memset.c",
                // "newlib/libc/machine/arm/strlen.c",
                // "newlib/libc/picolib/machine/arm/interrupt.c",
                // "newlib/libc/picolib/machine/arm/tls.c",
                // libm
                "newlib/libm/machine/arm/s_ceil.c",
                "newlib/libm/machine/arm/s_fabs.c",
                "newlib/libm/machine/arm/s_floor.c",
                "newlib/libm/machine/arm/s_fma_arm.c",
                "newlib/libm/machine/arm/s_nearbyint.c",
                "newlib/libm/machine/arm/s_rint.c",
                "newlib/libm/machine/arm/s_round.c",
                "newlib/libm/machine/arm/s_sqrt.c",
                "newlib/libm/machine/arm/s_trunc.c",
                "newlib/libm/machine/arm/sf_ceil.c",
                "newlib/libm/machine/arm/sf_fabs.c",
                "newlib/libm/machine/arm/sf_floor.c",
                "newlib/libm/machine/arm/sf_fma_arm.c",
                "newlib/libm/machine/arm/sf_nearbyint.c",
                "newlib/libm/machine/arm/sf_rint.c",
                "newlib/libm/machine/arm/sf_round.c",
                "newlib/libm/machine/arm/sf_sqrt.c",
                "newlib/libm/machine/arm/sf_trunc.c",
                // picocrt
                "picocrt/machine/arm/crt0.c",
            },
            .amdgcn => &.{
                "newlib/libc/machine/amdgcn/abort.c",
                "newlib/libc/machine/amdgcn/atexit.c",
                "newlib/libc/machine/amdgcn/getreent.c",
                "newlib/libc/machine/amdgcn/mlock.c",
                "newlib/libc/machine/amdgcn/signal.c",
            },
            .aarch64 => &.{
                "newlib/libc/machine/aarch64/memchr-stub.c",
                "newlib/libc/machine/aarch64/memcmp-stub.c",
                "newlib/libc/machine/aarch64/memcpy-stub.c",
                "newlib/libc/machine/aarch64/memmove-stub.c",
                "newlib/libc/machine/aarch64/memrchr-stub.c",
                "newlib/libc/machine/aarch64/memset-stub.c",
                "newlib/libc/machine/aarch64/rawmemchr-stub.c",
                "newlib/libc/machine/aarch64/stpcpy-stub.c",
                "newlib/libc/machine/aarch64/strchr-stub.c",
                "newlib/libc/machine/aarch64/strchrnul-stub.c",
                "newlib/libc/machine/aarch64/strcmp-stub.c",
                "newlib/libc/machine/aarch64/strcpy-stub.c",
                "newlib/libc/machine/aarch64/strlen-stub.c",
                "newlib/libc/machine/aarch64/strncmp-stub.c",
                "newlib/libc/machine/aarch64/strnlen-stub.c",
                "newlib/libc/machine/aarch64/strrchr-stub.c",
                "newlib/libc/picolib/machine/aarch64/tls.c",
                // libm
                "newlib/libm/machine/aarch64/s_ceil.c",
                "newlib/libm/machine/aarch64/s_fabs.c",
                "newlib/libm/machine/aarch64/s_floor.c",
                "newlib/libm/machine/aarch64/s_fma.c",
                "newlib/libm/machine/aarch64/s_fmax.c",
                "newlib/libm/machine/aarch64/s_fmin.c",
                "newlib/libm/machine/aarch64/s_llrint.c",
                "newlib/libm/machine/aarch64/s_llround.c",
                "newlib/libm/machine/aarch64/s_lrint.c",
                "newlib/libm/machine/aarch64/s_lround.c",
                "newlib/libm/machine/aarch64/s_nearbyint.c",
                "newlib/libm/machine/aarch64/s_rint.c",
                "newlib/libm/machine/aarch64/s_round.c",
                "newlib/libm/machine/aarch64/s_sqrt.c",
                "newlib/libm/machine/aarch64/s_trunc.c",
                "newlib/libm/machine/aarch64/sf_ceil.c",
                "newlib/libm/machine/aarch64/sf_fabs.c",
                "newlib/libm/machine/aarch64/sf_floor.c",
                "newlib/libm/machine/aarch64/sf_fma.c",
                "newlib/libm/machine/aarch64/sf_fmax.c",
                "newlib/libm/machine/aarch64/sf_fmin.c",
                "newlib/libm/machine/aarch64/sf_llrint.c",
                "newlib/libm/machine/aarch64/sf_llround.c",
                "newlib/libm/machine/aarch64/sf_lrint.c",
                "newlib/libm/machine/aarch64/sf_lround.c",
                "newlib/libm/machine/aarch64/sf_nearbyint.c",
                "newlib/libm/machine/aarch64/sf_rint.c",
                "newlib/libm/machine/aarch64/sf_round.c",
                "newlib/libm/machine/aarch64/sf_sqrt.c",
                "newlib/libm/machine/aarch64/sf_trunc.c",
                // picocrt
                "picocrt/machine/aarch64/crt0.c",
            },
            .arc => &.{
                "newlib/libc/machine/arc/memcmp-stub.c",
                "newlib/libc/machine/arc/memcpy-stub.c",
                "newlib/libc/machine/arc/memset-stub.c",
                "newlib/libc/machine/arc/strchr-stub.c",
                "newlib/libc/machine/arc/strcmp-stub.c",
                "newlib/libc/machine/arc/strcpy-stub.c",
                "newlib/libc/machine/arc/strlen-stub.c",
                "newlib/libc/machine/arc/strncpy-stub.c",
                "newlib/libc/picolib/machine/arc/tls.c",
                // picocrt
                "picocrt/machine/arc/crt0.c",
            },
            .m68k => &.{
                "newlib/libc/machine/m68k/strcpy.c",
                "newlib/libc/machine/m68k/strlen.c",
                //picocrt
                "picocrt/machine/m68k/crt0.c",
            },
            .spu_2 => &.{
                "newlib/libc/machine/spu/assert.c",
                "newlib/libc/machine/spu/calloc_ea.c",
                "newlib/libc/machine/spu/clearerr.c",
                "newlib/libc/machine/spu/creat.c",
                "newlib/libc/machine/spu/fclose.c",
                "newlib/libc/machine/spu/fdopen.c",
                "newlib/libc/machine/spu/feof.c",
                "newlib/libc/machine/spu/ferror.c",
                "newlib/libc/machine/spu/fflush.c",
                "newlib/libc/machine/spu/fgetc.c",
                "newlib/libc/machine/spu/fgetpos.c",
                "newlib/libc/machine/spu/fgets.c",
                "newlib/libc/machine/spu/fileno.c",
                "newlib/libc/machine/spu/fopen.c",
                "newlib/libc/machine/spu/fputc.c",
                "newlib/libc/machine/spu/fputs.c",
                "newlib/libc/machine/spu/fread.c",
                "newlib/libc/machine/spu/free_ea.c",
                "newlib/libc/machine/spu/freopen.c",
                "newlib/libc/machine/spu/fseek.c",
                "newlib/libc/machine/spu/fsetpos.c",
                "newlib/libc/machine/spu/ftell.c",
                "newlib/libc/machine/spu/fwrite.c",
                "newlib/libc/machine/spu/getc.c",
                "newlib/libc/machine/spu/getchar.c",
                "newlib/libc/machine/spu/gets.c",
                "newlib/libc/machine/spu/malloc_ea.c",
                "newlib/libc/machine/spu/memchr_ea.c",
                "newlib/libc/machine/spu/memcmp.c",
                "newlib/libc/machine/spu/memcmp_ea.c",
                "newlib/libc/machine/spu/memcpy.c",
                "newlib/libc/machine/spu/memcpy_ea.c",
                "newlib/libc/machine/spu/memmove.c",
                "newlib/libc/machine/spu/memmove_ea.c",
                "newlib/libc/machine/spu/memset.c",
                "newlib/libc/machine/spu/memset_ea.c",
                "newlib/libc/machine/spu/mmap_ea.c",
                "newlib/libc/machine/spu/mremap_ea.c",
                "newlib/libc/machine/spu/msync_ea.c",
                "newlib/libc/machine/spu/munmap_ea.c",
                "newlib/libc/machine/spu/perror.c",
                "newlib/libc/machine/spu/posix_memalign_ea.c",
                "newlib/libc/machine/spu/pread_ea.c",
                "newlib/libc/machine/spu/putc.c",
                "newlib/libc/machine/spu/putchar.c",
                "newlib/libc/machine/spu/puts.c",
                "newlib/libc/machine/spu/pwrite_ea.c",
                "newlib/libc/machine/spu/read_ea.c",
                "newlib/libc/machine/spu/readv_ea.c",
                "newlib/libc/machine/spu/realloc_ea.c",
                "newlib/libc/machine/spu/remove.c",
                "newlib/libc/machine/spu/rename.c",
                "newlib/libc/machine/spu/rewind.c",
                "newlib/libc/machine/spu/setbuf.c",
                "newlib/libc/machine/spu/setvbuf.c",
                "newlib/libc/machine/spu/sleep.c",
                "newlib/libc/machine/spu/spu-gmon.c",
                "newlib/libc/machine/spu/spu_clock_stop.c",
                "newlib/libc/machine/spu/spu_clock_svcs.c",
                "newlib/libc/machine/spu/spu_timebase.c",
                "newlib/libc/machine/spu/spu_timer_free.c",
                "newlib/libc/machine/spu/spu_timer_slih.c",
                "newlib/libc/machine/spu/spu_timer_slih_reg.c",
                "newlib/libc/machine/spu/spu_timer_stop.c",
                "newlib/libc/machine/spu/spu_timer_svcs.c",
                "newlib/libc/machine/spu/stdio.c",
                "newlib/libc/machine/spu/strcat.c",
                "newlib/libc/machine/spu/strcat_ea.c",
                "newlib/libc/machine/spu/strchr.c",
                "newlib/libc/machine/spu/strchr_ea.c",
                "newlib/libc/machine/spu/strcmp.c",
                "newlib/libc/machine/spu/strcmp_ea.c",
                "newlib/libc/machine/spu/strcpy.c",
                "newlib/libc/machine/spu/strcpy_ea.c",
                "newlib/libc/machine/spu/strcspn.c",
                "newlib/libc/machine/spu/strcspn_ea.c",
                "newlib/libc/machine/spu/strlen.c",
                "newlib/libc/machine/spu/strlen_ea.c",
                "newlib/libc/machine/spu/strncat.c",
                "newlib/libc/machine/spu/strncat_ea.c",
                "newlib/libc/machine/spu/strncmp.c",
                "newlib/libc/machine/spu/strncmp_ea.c",
                "newlib/libc/machine/spu/strncpy.c",
                "newlib/libc/machine/spu/strncpy_ea.c",
                "newlib/libc/machine/spu/strpbrk.c",
                "newlib/libc/machine/spu/strpbrk_ea.c",
                "newlib/libc/machine/spu/strrchr.c",
                "newlib/libc/machine/spu/strrchr_ea.c",
                "newlib/libc/machine/spu/strspn.c",
                "newlib/libc/machine/spu/strspn_ea.c",
                "newlib/libc/machine/spu/strstr_ea.c",
                "newlib/libc/machine/spu/strxfrm.c",
                "newlib/libc/machine/spu/tmpfile.c",
                "newlib/libc/machine/spu/tmpnam.c",
                "newlib/libc/machine/spu/ungetc.c",
                "newlib/libc/machine/spu/usleep.c",
                "newlib/libc/machine/spu/vfiprintf.c",
                "newlib/libc/machine/spu/vfiscanf.c",
                "newlib/libc/machine/spu/vfprintf.c",
                "newlib/libc/machine/spu/vfscanf.c",
                "newlib/libc/machine/spu/viprintf.c",
                "newlib/libc/machine/spu/viscanf.c",
                "newlib/libc/machine/spu/vprintf.c",
                "newlib/libc/machine/spu/vscanf.c",
                "newlib/libc/machine/spu/vsiprintf.c",
                "newlib/libc/machine/spu/vsiscanf.c",
                "newlib/libc/machine/spu/vsniprintf.c",
                "newlib/libc/machine/spu/vsnprintf.c",
                "newlib/libc/machine/spu/vsprintf.c",
                "newlib/libc/machine/spu/vsscanf.c",
                "newlib/libc/machine/spu/write_ea.c",
                "newlib/libc/machine/spu/writev_ea.c",
                // libm
                "newlib/libm/machine/spu/llrint.c",
                "newlib/libm/machine/spu/llrintf.c",
                "newlib/libm/machine/spu/llround.c",
                "newlib/libm/machine/spu/llroundf.c",
                "newlib/libm/machine/spu/log2.c",
                "newlib/libm/machine/spu/log2f.c",
                "newlib/libm/machine/spu/s_asinh.c",
                "newlib/libm/machine/spu/s_atan.c",
                "newlib/libm/machine/spu/s_cbrt.c",
                "newlib/libm/machine/spu/s_ceil.c",
                "newlib/libm/machine/spu/s_copysign.c",
                "newlib/libm/machine/spu/s_cos.c",
                "newlib/libm/machine/spu/s_erf.c",
                "newlib/libm/machine/spu/s_expm1.c",
                "newlib/libm/machine/spu/s_fabs.c",
                "newlib/libm/machine/spu/s_fdim.c",
                "newlib/libm/machine/spu/s_floor.c",
                "newlib/libm/machine/spu/s_fma.c",
                "newlib/libm/machine/spu/s_fmax.c",
                "newlib/libm/machine/spu/s_fmin.c",
                "newlib/libm/machine/spu/s_frexp.c",
                "newlib/libm/machine/spu/s_ilogb.c",
                "newlib/libm/machine/spu/s_isnan.c",
                "newlib/libm/machine/spu/s_ldexp.c",
                "newlib/libm/machine/spu/s_log1p.c",
                "newlib/libm/machine/spu/s_lrint.c",
                "newlib/libm/machine/spu/s_lround.c",
                "newlib/libm/machine/spu/s_nearbyint.c",
                "newlib/libm/machine/spu/s_nextafter.c",
                "newlib/libm/machine/spu/s_remquo.c",
                "newlib/libm/machine/spu/s_rint.c",
                "newlib/libm/machine/spu/s_round.c",
                "newlib/libm/machine/spu/s_scalbn.c",
                "newlib/libm/machine/spu/s_sin.c",
                "newlib/libm/machine/spu/s_tan.c",
                "newlib/libm/machine/spu/s_tanh.c",
                "newlib/libm/machine/spu/s_trunc.c",
                "newlib/libm/machine/spu/sf_asinh.c",
                "newlib/libm/machine/spu/sf_atan.c",
                "newlib/libm/machine/spu/sf_cbrt.c",
                "newlib/libm/machine/spu/sf_ceil.c",
                "newlib/libm/machine/spu/sf_copysign.c",
                "newlib/libm/machine/spu/sf_cos.c",
                "newlib/libm/machine/spu/sf_erf.c",
                "newlib/libm/machine/spu/sf_expm1.c",
                "newlib/libm/machine/spu/sf_fabs.c",
                "newlib/libm/machine/spu/sf_fdim.c",
                "newlib/libm/machine/spu/sf_finite.c",
                "newlib/libm/machine/spu/sf_floor.c",
                "newlib/libm/machine/spu/sf_fma.c",
                "newlib/libm/machine/spu/sf_fmax.c",
                "newlib/libm/machine/spu/sf_fmin.c",
                "newlib/libm/machine/spu/sf_fpclassify.c",
                "newlib/libm/machine/spu/sf_frexp.c",
                "newlib/libm/machine/spu/sf_ilogb.c",
                "newlib/libm/machine/spu/sf_isinf.c",
                "newlib/libm/machine/spu/sf_isinff.c",
                "newlib/libm/machine/spu/sf_isnan.c",
                "newlib/libm/machine/spu/sf_isnanf.c",
                "newlib/libm/machine/spu/sf_ldexp.c",
                "newlib/libm/machine/spu/sf_log1p.c",
                "newlib/libm/machine/spu/sf_logb.c",
                "newlib/libm/machine/spu/sf_lrint.c",
                "newlib/libm/machine/spu/sf_lround.c",
                "newlib/libm/machine/spu/sf_nan.c",
                "newlib/libm/machine/spu/sf_nearbyint.c",
                "newlib/libm/machine/spu/sf_nextafter.c",
                "newlib/libm/machine/spu/sf_remquo.c",
                "newlib/libm/machine/spu/sf_rint.c",
                "newlib/libm/machine/spu/sf_round.c",
                "newlib/libm/machine/spu/sf_scalbn.c",
                "newlib/libm/machine/spu/sf_sin.c",
                "newlib/libm/machine/spu/sf_tan.c",
                "newlib/libm/machine/spu/sf_tanh.c",
                "newlib/libm/machine/spu/sf_trunc.c",
                "newlib/libm/machine/spu/w_acos.c",
                "newlib/libm/machine/spu/w_acosh.c",
                "newlib/libm/machine/spu/w_asin.c",
                "newlib/libm/machine/spu/w_atan2.c",
                "newlib/libm/machine/spu/w_atanh.c",
                "newlib/libm/machine/spu/w_cosh.c",
                "newlib/libm/machine/spu/w_exp.c",
                "newlib/libm/machine/spu/w_exp2.c",
                "newlib/libm/machine/spu/w_fmod.c",
                "newlib/libm/machine/spu/w_hypot.c",
                "newlib/libm/machine/spu/w_lgamma.c",
                "newlib/libm/machine/spu/w_log.c",
                "newlib/libm/machine/spu/w_log10.c",
                "newlib/libm/machine/spu/w_pow.c",
                "newlib/libm/machine/spu/w_remainder.c",
                "newlib/libm/machine/spu/w_sincos.c",
                "newlib/libm/machine/spu/w_sinh.c",
                "newlib/libm/machine/spu/w_sqrt.c",
                "newlib/libm/machine/spu/w_tgamma.c",
                "newlib/libm/machine/spu/wf_acos.c",
                "newlib/libm/machine/spu/wf_acosh.c",
                "newlib/libm/machine/spu/wf_asin.c",
                "newlib/libm/machine/spu/wf_atan2.c",
                "newlib/libm/machine/spu/wf_atanh.c",
                "newlib/libm/machine/spu/wf_cosh.c",
                "newlib/libm/machine/spu/wf_exp.c",
                "newlib/libm/machine/spu/wf_exp2.c",
                "newlib/libm/machine/spu/wf_fmod.c",
                "newlib/libm/machine/spu/wf_hypot.c",
                "newlib/libm/machine/spu/wf_lgamma.c",
                "newlib/libm/machine/spu/wf_log.c",
                "newlib/libm/machine/spu/wf_log10.c",
                "newlib/libm/machine/spu/wf_pow.c",
                "newlib/libm/machine/spu/wf_remainder.c",
                "newlib/libm/machine/spu/wf_sincos.c",
                "newlib/libm/machine/spu/wf_sinh.c",
                "newlib/libm/machine/spu/wf_sqrt.c",
                "newlib/libm/machine/spu/wf_tgamma.c",
            },
            .mips, .mipsel => &.{
                "newlib/libc/machine/mips/strlen.c",
                "newlib/libc/machine/mips/strncpy.c",
                "newlib/libc/picolib/machine/mips/tls.c",
                // picocrt
                "picocrt/machine/mips/crt0.c",
            },
            .nvptx => &.{
                "newlib/libc/machine/nvptx/_exit.c",
                "newlib/libc/machine/nvptx/abort.c",
                "newlib/libc/machine/nvptx/assert.c",
                "newlib/libc/machine/nvptx/calloc.c",
                "newlib/libc/machine/nvptx/callocr.c",
                "newlib/libc/machine/nvptx/clock.c",
                "newlib/libc/machine/nvptx/free.c",
                "newlib/libc/machine/nvptx/malloc.c",
                "newlib/libc/machine/nvptx/mallocr.c",
                "newlib/libc/machine/nvptx/misc.c",
                "newlib/libc/machine/nvptx/printf.c",
                "newlib/libc/machine/nvptx/putchar.c",
                "newlib/libc/machine/nvptx/puts.c",
                "newlib/libc/machine/nvptx/realloc.c",
                "newlib/libc/machine/nvptx/reallocr.c",
                "newlib/libc/machine/nvptx/write.c",
            },
            .sparc => &.{
                "newlib/libc/machine/sparc/scan.c",
                "newlib/libc/machine/sparc/shuffle.c",
                "newlib/libc/picolib/machine/sparc/tls.c",
                // picocrt
                "picocrt/machine/sparc/crt0.c",
            },
            .riscv32, .riscv64 => &.{
                "newlib/libc/picolib/machine/riscv/tls.c",
                "newlib/libc/machine/riscv/ieeefp.c",
                "newlib/libc/machine/riscv/memcpy.c",
                "newlib/libc/machine/riscv/memmove-stub.c",
                "newlib/libc/machine/riscv/strcpy.c",
                "newlib/libc/machine/riscv/strlen.c",
                // libm
                "newlib/libm/machine/riscv/s_copysign.c",
                "newlib/libm/machine/riscv/s_fabs.c",
                "newlib/libm/machine/riscv/s_finite.c",
                "newlib/libm/machine/riscv/s_fma.c",
                "newlib/libm/machine/riscv/s_fmax.c",
                "newlib/libm/machine/riscv/s_fmin.c",
                "newlib/libm/machine/riscv/s_fpclassify.c",
                "newlib/libm/machine/riscv/s_isinf.c",
                "newlib/libm/machine/riscv/s_isnan.c",
                "newlib/libm/machine/riscv/s_llrint.c",
                "newlib/libm/machine/riscv/s_llround.c",
                "newlib/libm/machine/riscv/s_lrint.c",
                "newlib/libm/machine/riscv/s_lround.c",
                "newlib/libm/machine/riscv/s_sqrt.c",
                "newlib/libm/machine/riscv/sf_copysign.c",
                "newlib/libm/machine/riscv/sf_fabs.c",
                "newlib/libm/machine/riscv/sf_finite.c",
                "newlib/libm/machine/riscv/sf_fma.c",
                "newlib/libm/machine/riscv/sf_fmax.c",
                "newlib/libm/machine/riscv/sf_fmin.c",
                "newlib/libm/machine/riscv/sf_fpclassify.c",
                "newlib/libm/machine/riscv/sf_isinf.c",
                "newlib/libm/machine/riscv/sf_isnan.c",
                "newlib/libm/machine/riscv/sf_llrint.c",
                "newlib/libm/machine/riscv/sf_llround.c",
                "newlib/libm/machine/riscv/sf_lrint.c",
                "newlib/libm/machine/riscv/sf_lround.c",
                "newlib/libm/machine/riscv/sf_sqrt.c",
                // picocrt
                "picocrt/machine/riscv/crt0.c",
            },
            .x86, .x86_64 => &.{
                "newlib/libc/machine/x86/memchr.c",
                "newlib/libc/machine/x86/memcmp.c",
                "newlib/libc/machine/x86/memmove.c",
                "newlib/libc/machine/x86/strchr.c",
                "newlib/libc/machine/x86/strlen.c",
                // libm
                "newlib/libm/machine/x86/f_exp.c",
                "newlib/libm/machine/x86/f_expf.c",
                "newlib/libm/machine/x86/f_llrint.c",
                "newlib/libm/machine/x86/f_llrintf.c",
                "newlib/libm/machine/x86/f_llrintl.c",
                "newlib/libm/machine/x86/f_lrint.c",
                "newlib/libm/machine/x86/f_lrintf.c",
                "newlib/libm/machine/x86/f_lrintl.c",
                "newlib/libm/machine/x86/f_pow.c",
                "newlib/libm/machine/x86/f_powf.c",
                "newlib/libm/machine/x86/f_rint.c",
                "newlib/libm/machine/x86/f_rintf.c",
                "newlib/libm/machine/x86/f_rintl.c",
                // "newlib/libm/machine/x86/fenv.c",
            },
            .xtensa => &.{
                "newlib/libc/sys/xtensa/clibrary_init.c",
                "newlib/libc/sys/xtensa/creat.c",
                "newlib/libc/sys/xtensa/crt0.c",
                // "newlib/libc/sys/xtensa/isatty.c",
                // "newlib/libc/picolib/machine/xtensa/tls.c",
            },
            else => &.{},
        },
        .flags = cflags,
    });
    newlib.installHeadersDirectory(
        b.path("newlib/libc/include"),
        "",
        .{
            .exclude_extensions = &.{
                "c",
                "build",
                "txt",
                "tex",
            },
        },
    );
    newlib.installHeadersDirectory(
        b.path("newlib/libc/stdio"),
        "",
        .{
            .exclude_extensions = &.{
                "c",
                "build",
                "txt",
                "tex",
            },
        },
    );

    newlib.installHeader(picolibc_h.getOutput(), "picolibc.h");
    b.installArtifact(newlib);

    // fixme: linking newlib to hello-world
    // const hello = b.addExecutable(.{
    //     .name = "hello_c",
    //     .target = target,
    //     .optimize = optimize,
    // });
    // for (newlib.root_module.include_dirs.items) |include_dir| {
    //     try hello.root_module.include_dirs.append(b.allocator, include_dir);
    // }
    // hello.addCSourceFile(.{
    //     .file = b.path("hello-world/hello-world.c" },
    //     .flags = cflags,
    // });
    // const link_libcxx = hello.root_module.link_libcpp orelse false;
    // hello.setLinkerScript(b.path(switch (hello.rootModuleTarget().cpu.arch) {
    //     .riscv32, .riscv64 => if (link_libcxx) "hello-world/riscv-cpp.ld" else "hello-world/riscv.ld",
    //     .arm, .armeb => if (link_libcxx) "hello-world/arm-cpp.ld" else "hello-world/arm.ld",
    //     .aarch64, .aarch64_be => if (link_libcxx) "hello-world/aarch64-cpp.ld" else "hello-world/aarch64.ld",
    //     else => if (link_libcxx) "hello-world/picolibcpp.ld" else "hello-world/picolibc.ld",
    // } });

    // hello.setLinkerScript(b.path("hello-world/picolibc.ld" });
    // hello.linkLibrary(newlib);
    // b.installArtifact(hello);
}
const cflags = &.{
    "-fno-common",
    "-fno-stack-protector",
    "-ffunction-sections",
    "-fdata-sections",
    "-Wall",
    "-Wextra",
    "-Werror=implicit-function-declaration",
    "-Werror=vla",
    "-Warray-bounds",
    "-Wold-style-definition",
    "-frounding-math",
    "-fsignaling-nans",
};
const libc = &.{
    "picocrt/shared/crt0.c",
    "newlib/libc/argz/argz_add.c",
    "newlib/libc/argz/argz_add_sep.c",
    "newlib/libc/argz/argz_append.c",
    "newlib/libc/argz/argz_count.c",
    "newlib/libc/argz/argz_create.c",
    "newlib/libc/argz/argz_create_sep.c",
    "newlib/libc/argz/argz_delete.c",
    "newlib/libc/argz/argz_extract.c",
    "newlib/libc/argz/argz_insert.c",
    "newlib/libc/argz/argz_next.c",
    "newlib/libc/argz/argz_replace.c",
    "newlib/libc/argz/argz_stringify.c",
    "newlib/libc/argz/buf_findstr.c",
    "newlib/libc/argz/envz_add.c",
    "newlib/libc/argz/envz_entry.c",
    "newlib/libc/argz/envz_get.c",
    "newlib/libc/argz/envz_merge.c",
    "newlib/libc/argz/envz_remove.c",
    "newlib/libc/argz/envz_strip.c",
    "newlib/libc/ctype/categories.c",
    "newlib/libc/ctype/ctype_.c",
    "newlib/libc/ctype/isalnum.c",
    "newlib/libc/ctype/isalnum_l.c",
    "newlib/libc/ctype/isalpha.c",
    "newlib/libc/ctype/isalpha_l.c",
    "newlib/libc/ctype/isascii.c",
    "newlib/libc/ctype/isascii_l.c",
    "newlib/libc/ctype/isblank.c",
    "newlib/libc/ctype/isblank_l.c",
    "newlib/libc/ctype/iscntrl.c",
    "newlib/libc/ctype/iscntrl_l.c",
    "newlib/libc/ctype/isdigit.c",
    "newlib/libc/ctype/isdigit_l.c",
    "newlib/libc/ctype/isgraph.c",
    "newlib/libc/ctype/isgraph_l.c",
    "newlib/libc/ctype/islower.c",
    "newlib/libc/ctype/islower_l.c",
    "newlib/libc/ctype/isprint.c",
    "newlib/libc/ctype/isprint_l.c",
    "newlib/libc/ctype/ispunct.c",
    "newlib/libc/ctype/ispunct_l.c",
    "newlib/libc/ctype/isspace.c",
    "newlib/libc/ctype/isspace_l.c",
    "newlib/libc/ctype/isupper.c",
    "newlib/libc/ctype/isupper_l.c",
    "newlib/libc/ctype/iswalnum.c",
    "newlib/libc/ctype/iswalnum_l.c",
    "newlib/libc/ctype/iswalpha.c",
    "newlib/libc/ctype/iswalpha_l.c",
    "newlib/libc/ctype/iswblank.c",
    "newlib/libc/ctype/iswblank_l.c",
    "newlib/libc/ctype/iswcntrl.c",
    "newlib/libc/ctype/iswcntrl_l.c",
    "newlib/libc/ctype/iswctype.c",
    "newlib/libc/ctype/iswctype_l.c",
    "newlib/libc/ctype/iswdigit.c",
    "newlib/libc/ctype/iswdigit_l.c",
    "newlib/libc/ctype/iswgraph.c",
    "newlib/libc/ctype/iswgraph_l.c",
    "newlib/libc/ctype/iswlower.c",
    "newlib/libc/ctype/iswlower_l.c",
    "newlib/libc/ctype/iswprint.c",
    "newlib/libc/ctype/iswprint_l.c",
    "newlib/libc/ctype/iswpunct.c",
    "newlib/libc/ctype/iswpunct_l.c",
    "newlib/libc/ctype/iswspace.c",
    "newlib/libc/ctype/iswspace_l.c",
    "newlib/libc/ctype/iswupper.c",
    "newlib/libc/ctype/iswupper_l.c",
    "newlib/libc/ctype/iswxdigit.c",
    "newlib/libc/ctype/iswxdigit_l.c",
    "newlib/libc/ctype/isxdigit.c",
    "newlib/libc/ctype/isxdigit_l.c",
    "newlib/libc/ctype/jp2uc.c",
    "newlib/libc/ctype/toascii.c",
    "newlib/libc/ctype/toascii_l.c",
    "newlib/libc/ctype/tolower.c",
    "newlib/libc/ctype/tolower_l.c",
    "newlib/libc/ctype/toupper.c",
    "newlib/libc/ctype/toupper_l.c",
    "newlib/libc/ctype/towctrans.c",
    "newlib/libc/ctype/towctrans_l.c",
    "newlib/libc/ctype/towlower.c",
    "newlib/libc/ctype/towlower_l.c",
    "newlib/libc/ctype/towupper.c",
    "newlib/libc/ctype/towupper_l.c",
    "newlib/libc/ctype/wctrans.c",
    "newlib/libc/ctype/wctrans_l.c",
    "newlib/libc/ctype/wctype.c",
    "newlib/libc/ctype/wctype_l.c",
    "newlib/libc/errno/errno.c",
    "newlib/libc/iconv/ccs/big5.c",
    "newlib/libc/iconv/ccs/ccsbi.c",
    "newlib/libc/iconv/ccs/cns11643_plane1.c",
    "newlib/libc/iconv/ccs/cns11643_plane14.c",
    "newlib/libc/iconv/ccs/cns11643_plane2.c",
    "newlib/libc/iconv/ccs/cp775.c",
    "newlib/libc/iconv/ccs/cp850.c",
    "newlib/libc/iconv/ccs/cp852.c",
    "newlib/libc/iconv/ccs/cp855.c",
    "newlib/libc/iconv/ccs/cp866.c",
    "newlib/libc/iconv/ccs/iso_8859_1.c",
    "newlib/libc/iconv/ccs/iso_8859_10.c",
    "newlib/libc/iconv/ccs/iso_8859_11.c",
    "newlib/libc/iconv/ccs/iso_8859_13.c",
    "newlib/libc/iconv/ccs/iso_8859_14.c",
    "newlib/libc/iconv/ccs/iso_8859_15.c",
    "newlib/libc/iconv/ccs/iso_8859_2.c",
    "newlib/libc/iconv/ccs/iso_8859_3.c",
    "newlib/libc/iconv/ccs/iso_8859_4.c",
    "newlib/libc/iconv/ccs/iso_8859_5.c",
    "newlib/libc/iconv/ccs/iso_8859_6.c",
    "newlib/libc/iconv/ccs/iso_8859_7.c",
    "newlib/libc/iconv/ccs/iso_8859_8.c",
    "newlib/libc/iconv/ccs/iso_8859_9.c",
    "newlib/libc/iconv/ccs/iso_ir_111.c",
    "newlib/libc/iconv/ccs/jis_x0201_1976.c",
    "newlib/libc/iconv/ccs/jis_x0208_1990.c",
    "newlib/libc/iconv/ccs/jis_x0212_1990.c",
    "newlib/libc/iconv/ccs/koi8_r.c",
    "newlib/libc/iconv/ccs/koi8_ru.c",
    "newlib/libc/iconv/ccs/koi8_u.c",
    "newlib/libc/iconv/ccs/koi8_uni.c",
    "newlib/libc/iconv/ccs/ksx1001.c",
    "newlib/libc/iconv/ccs/win_1250.c",
    "newlib/libc/iconv/ccs/win_1251.c",
    "newlib/libc/iconv/ccs/win_1252.c",
    "newlib/libc/iconv/ccs/win_1253.c",
    "newlib/libc/iconv/ccs/win_1254.c",
    "newlib/libc/iconv/ccs/win_1255.c",
    "newlib/libc/iconv/ccs/win_1256.c",
    "newlib/libc/iconv/ccs/win_1257.c",
    "newlib/libc/iconv/ccs/win_1258.c",
    "newlib/libc/iconv/ces/cesbi.c",
    "newlib/libc/iconv/ces/euc.c",
    "newlib/libc/iconv/ces/table-pcs.c",
    "newlib/libc/iconv/ces/table.c",
    "newlib/libc/iconv/ces/ucs-2-internal.c",
    "newlib/libc/iconv/ces/ucs-2.c",
    "newlib/libc/iconv/ces/ucs-4-internal.c",
    "newlib/libc/iconv/ces/ucs-4.c",
    "newlib/libc/iconv/ces/us-ascii.c",
    "newlib/libc/iconv/ces/utf-16.c",
    "newlib/libc/iconv/ces/utf-8.c",
    "newlib/libc/iconv/lib/aliasesbi.c",
    "newlib/libc/iconv/lib/aliasesi.c",
    "newlib/libc/iconv/lib/iconv.c",
    "newlib/libc/iconv/lib/iconvnls.c",
    "newlib/libc/iconv/lib/nullconv.c",
    "newlib/libc/iconv/lib/ucsconv.c",
    "newlib/libc/locale/duplocale.c",
    "newlib/libc/locale/freelocale.c",
    "newlib/libc/locale/lctype.c",
    "newlib/libc/locale/lmessages.c",
    "newlib/libc/locale/lmonetary.c",
    "newlib/libc/locale/lnumeric.c",
    "newlib/libc/locale/locale.c",
    "newlib/libc/locale/localeconv.c",
    "newlib/libc/locale/newlocale.c",
    "newlib/libc/locale/nl_langinfo.c",
    "newlib/libc/locale/timelocal.c",
    "newlib/libc/locale/uselocale.c",
    "newlib/libc/misc/__dprintf.c",
    "newlib/libc/misc/ffs.c",
    "newlib/libc/misc/fini.c",
    "newlib/libc/misc/init.c",
    "newlib/libc/misc/lock.c",
    "newlib/libc/misc/ubsan.c",
    "newlib/libc/misc/unctrl.c",
    "newlib/libc/picolib/dso_handle.c",
    "newlib/libc/picolib/getauxval.c",
    "newlib/libc/picolib/inittls.c",
    "newlib/libc/picolib/picosbrk.c",
    // "newlib/libc/posix/basename.c",
    // "newlib/libc/posix/collate.c",
    // "newlib/libc/posix/collcmp.c",
    // "newlib/libc/posix/dirname.c",
    // "newlib/libc/posix/engine.c",
    // "newlib/libc/posix/fnmatch.c",
    // "newlib/libc/posix/ftw.c",
    // "newlib/libc/posix/nftw.c",
    // "newlib/libc/posix/regcomp.c",
    // "newlib/libc/posix/regerror.c",
    // "newlib/libc/posix/regexec.c",
    // "newlib/libc/posix/regfree.c",
    "newlib/libc/reent/reent.c",
    "newlib/libc/search/bsd_qsort_r.c",
    "newlib/libc/search/bsearch.c",
    "newlib/libc/search/hash.c",
    "newlib/libc/search/hash_bigkey.c",
    "newlib/libc/search/hash_buf.c",
    "newlib/libc/search/hash_func.c",
    "newlib/libc/search/hash_log2.c",
    "newlib/libc/search/hash_page.c",
    "newlib/libc/search/hcreate.c",
    "newlib/libc/search/hcreate_r.c",
    "newlib/libc/search/ndbm.c",
    "newlib/libc/search/qsort.c",
    "newlib/libc/search/qsort_r.c",
    "newlib/libc/search/tdelete.c",
    "newlib/libc/search/tdestroy.c",
    "newlib/libc/search/tfind.c",
    "newlib/libc/search/tsearch.c",
    "newlib/libc/search/twalk.c",
    "newlib/libc/signal/psignal.c",
    "newlib/libc/signal/sig2str.c",
    "newlib/libc/signal/signal.c",
    "newlib/libc/ssp/chk_fail.c",
    "newlib/libc/ssp/gets_chk.c",
    "newlib/libc/ssp/memcpy_chk.c",
    "newlib/libc/ssp/memmove_chk.c",
    "newlib/libc/ssp/mempcpy_chk.c",
    "newlib/libc/ssp/memset_chk.c",
    "newlib/libc/ssp/snprintf_chk.c",
    "newlib/libc/ssp/sprintf_chk.c",
    "newlib/libc/ssp/stack_protector.c",
    "newlib/libc/ssp/stpcpy_chk.c",
    "newlib/libc/ssp/stpncpy_chk.c",
    "newlib/libc/ssp/strcat_chk.c",
    "newlib/libc/ssp/strcpy_chk.c",
    "newlib/libc/ssp/strncat_chk.c",
    "newlib/libc/ssp/strncpy_chk.c",
    "newlib/libc/ssp/vsnprintf_chk.c",
    "newlib/libc/ssp/vsprintf_chk.c",

    "newlib/libc/stdio/asiprintf.c",
    "newlib/libc/stdio/asniprintf.c",
    "newlib/libc/stdio/asnprintf.c",
    "newlib/libc/stdio/asprintf.c",
    "newlib/libc/stdio/clearerr.c",
    "newlib/libc/stdio/clearerr_u.c",
    "newlib/libc/stdio/diprintf.c",
    "newlib/libc/stdio/dprintf.c",
    "newlib/libc/stdio/fclose.c",
    "newlib/libc/stdio/fcloseall.c",
    "newlib/libc/stdio/fdopen.c",
    "newlib/libc/stdio/feof.c",
    "newlib/libc/stdio/feof_u.c",
    "newlib/libc/stdio/ferror.c",
    "newlib/libc/stdio/ferror_u.c",
    "newlib/libc/stdio/fflush.c",
    "newlib/libc/stdio/fflush_u.c",
    "newlib/libc/stdio/fgetc.c",
    "newlib/libc/stdio/fgetc_u.c",
    "newlib/libc/stdio/fgetpos.c",
    "newlib/libc/stdio/fgets.c",
    "newlib/libc/stdio/fgets_u.c",
    "newlib/libc/stdio/fgetwc.c",
    "newlib/libc/stdio/fgetwc_u.c",
    "newlib/libc/stdio/fgetws.c",
    "newlib/libc/stdio/fgetws_u.c",
    "newlib/libc/stdio/fileno.c",
    "newlib/libc/stdio/fileno_u.c",
    "newlib/libc/stdio/findfp.c",
    "newlib/libc/stdio/fiprintf.c",
    "newlib/libc/stdio/fiscanf.c",
    "newlib/libc/stdio/flags.c",
    "newlib/libc/stdio/fmemopen.c",
    "newlib/libc/stdio/fopen.c",
    "newlib/libc/stdio/fopencookie.c",
    "newlib/libc/stdio/fprintf.c",
    "newlib/libc/stdio/fpurge.c",
    "newlib/libc/stdio/fputc.c",
    "newlib/libc/stdio/fputc_u.c",
    "newlib/libc/stdio/fputs.c",
    "newlib/libc/stdio/fputs_u.c",
    "newlib/libc/stdio/fputwc.c",
    "newlib/libc/stdio/fputwc_u.c",
    "newlib/libc/stdio/fputws.c",
    "newlib/libc/stdio/fputws_u.c",
    "newlib/libc/stdio/fread.c",
    "newlib/libc/stdio/fread_u.c",
    "newlib/libc/stdio/freopen.c",
    "newlib/libc/stdio/fscanf.c",
    "newlib/libc/stdio/fseek.c",
    "newlib/libc/stdio/fseeko.c",
    "newlib/libc/stdio/fsetlocking.c",
    "newlib/libc/stdio/fsetpos.c",
    "newlib/libc/stdio/ftell.c",
    "newlib/libc/stdio/ftello.c",
    "newlib/libc/stdio/funopen.c",
    "newlib/libc/stdio/fvwrite.c",
    "newlib/libc/stdio/fwalk.c",
    "newlib/libc/stdio/fwide.c",
    "newlib/libc/stdio/fwprintf.c",
    "newlib/libc/stdio/fwrite.c",
    "newlib/libc/stdio/fwrite_u.c",
    "newlib/libc/stdio/fwscanf.c",
    "newlib/libc/stdio/getc.c",
    "newlib/libc/stdio/getc_u.c",
    "newlib/libc/stdio/getchar.c",
    "newlib/libc/stdio/getchar_u.c",
    "newlib/libc/stdio/getdelim.c",
    "newlib/libc/stdio/getline.c",
    "newlib/libc/stdio/gets.c",
    "newlib/libc/stdio/getw.c",
    "newlib/libc/stdio/getwc.c",
    "newlib/libc/stdio/getwc_u.c",
    "newlib/libc/stdio/getwchar.c",
    "newlib/libc/stdio/getwchar_u.c",
    "newlib/libc/stdio/iprintf.c",
    "newlib/libc/stdio/iscanf.c",
    "newlib/libc/stdio/makebuf.c",
    "newlib/libc/stdio/mktemp.c",
    // "newlib/libc/stdio/nano-svfprintf.c",
    // "newlib/libc/stdio/nano-svfscanf.c",
    // "newlib/libc/stdio/nano-vfprintf.c",
    // "newlib/libc/stdio/nano-vfprintf_float.c",
    // "newlib/libc/stdio/nano-vfprintf_i.c",
    // "newlib/libc/stdio/nano-vfscanf.c",
    // "newlib/libc/stdio/nano-vfscanf_float.c",
    // "newlib/libc/stdio/nano-vfscanf_i.c",
    // "newlib/libc/stdio/open_memstream.c",
    "newlib/libc/stdio/perror.c",
    "newlib/libc/stdio/printf.c",
    "newlib/libc/stdio/putc.c",
    "newlib/libc/stdio/putc_u.c",
    "newlib/libc/stdio/putchar.c",
    "newlib/libc/stdio/putchar_u.c",
    "newlib/libc/stdio/puts.c",
    "newlib/libc/stdio/putw.c",
    "newlib/libc/stdio/putwc.c",
    "newlib/libc/stdio/putwc_u.c",
    "newlib/libc/stdio/putwchar.c",
    "newlib/libc/stdio/putwchar_u.c",
    "newlib/libc/stdio/refill.c",
    "newlib/libc/stdio/remove.c",
    "newlib/libc/stdio/rename.c",
    "newlib/libc/stdio/rewind.c",
    "newlib/libc/stdio/rget.c",
    "newlib/libc/stdio/scanf.c",
    "newlib/libc/stdio/sccl.c",
    "newlib/libc/stdio/setbuf.c",
    "newlib/libc/stdio/setbuffer.c",
    "newlib/libc/stdio/setlinebuf.c",
    "newlib/libc/stdio/setvbuf.c",
    "newlib/libc/stdio/sfputs.c",
    "newlib/libc/stdio/sfputws.c",
    "newlib/libc/stdio/siprintf.c",
    "newlib/libc/stdio/siscanf.c",
    "newlib/libc/stdio/sniprintf.c",
    "newlib/libc/stdio/snprintf.c",
    "newlib/libc/stdio/sprint.c",
    "newlib/libc/stdio/sprintf.c",
    "newlib/libc/stdio/sscanf.c",
    "newlib/libc/stdio/ssprint.c",
    "newlib/libc/stdio/ssputs.c",
    "newlib/libc/stdio/ssputws.c",
    "newlib/libc/stdio/sswprint.c",
    "newlib/libc/stdio/stdio.c",
    "newlib/libc/stdio/stdio_ext.c",
    "newlib/libc/stdio/svfiprintf.c",
    "newlib/libc/stdio/svfiscanf.c",
    "newlib/libc/stdio/svfiwprintf.c",
    "newlib/libc/stdio/svfiwscanf.c",
    "newlib/libc/stdio/svfprintf.c",
    "newlib/libc/stdio/svfscanf.c",
    "newlib/libc/stdio/svfwprintf.c",
    "newlib/libc/stdio/svfwscanf.c",
    "newlib/libc/stdio/swprint.c",
    "newlib/libc/stdio/swprintf.c",
    "newlib/libc/stdio/swscanf.c",
    "newlib/libc/stdio/tmpfile.c",
    "newlib/libc/stdio/tmpnam.c",
    "newlib/libc/stdio/ungetc.c",
    "newlib/libc/stdio/ungetwc.c",
    "newlib/libc/stdio/vasiprintf.c",
    "newlib/libc/stdio/vasniprintf.c",
    "newlib/libc/stdio/vasnprintf.c",
    "newlib/libc/stdio/vasprintf.c",
    "newlib/libc/stdio/vdiprintf.c",
    "newlib/libc/stdio/vdprintf.c",
    "newlib/libc/stdio/vfiprintf.c",
    "newlib/libc/stdio/vfiscanf.c",
    "newlib/libc/stdio/vfiwprintf.c",
    "newlib/libc/stdio/vfiwscanf.c",
    "newlib/libc/stdio/vfprintf.c",
    "newlib/libc/stdio/vfscanf.c",
    "newlib/libc/stdio/vfwprintf.c",
    "newlib/libc/stdio/vfwscanf.c",
    "newlib/libc/stdio/viprintf.c",
    "newlib/libc/stdio/viscanf.c",
    "newlib/libc/stdio/vprintf.c",
    "newlib/libc/stdio/vscanf.c",
    // "newlib/libc/stdio/vsiprintf.c",
    // "newlib/libc/stdio/vsiscanf.c",
    // "newlib/libc/stdio/vsniprintf.c",
    // "newlib/libc/stdio/vsnprintf.c",
    "newlib/libc/stdio/vsprintf.c",
    "newlib/libc/stdio/vsscanf.c",
    "newlib/libc/stdio/vswprintf.c",
    "newlib/libc/stdio/vswscanf.c",
    "newlib/libc/stdio/vwprintf.c",
    "newlib/libc/stdio/vwscanf.c",
    "newlib/libc/stdio/wbuf.c",
    "newlib/libc/stdio/wbufw.c",
    "newlib/libc/stdio/wprintf.c",
    "newlib/libc/stdio/wscanf.c",
    "newlib/libc/stdio/wsetup.c",
    // "newlib/libc/stdio64/fdopen64.c",
    // "newlib/libc/stdio64/fgetpos64.c",
    // "newlib/libc/stdio64/fopen64.c",
    // "newlib/libc/stdio64/freopen64.c",
    // "newlib/libc/stdio64/fseeko64.c",
    // "newlib/libc/stdio64/fsetpos64.c",
    // "newlib/libc/stdio64/ftello64.c",
    // "newlib/libc/stdio64/stdio64.c",
    // "newlib/libc/stdio64/tmpfile64.c",
    "newlib/libc/stdlib/_Exit.c",
    "newlib/libc/stdlib/__atexit.c",
    "newlib/libc/stdlib/__call_atexit.c",
    "newlib/libc/stdlib/a64l.c",
    "newlib/libc/stdlib/abort.c",
    "newlib/libc/stdlib/abs.c",
    "newlib/libc/stdlib/aligned_alloc.c",
    "newlib/libc/stdlib/arc4random.c",
    "newlib/libc/stdlib/arc4random_uniform.c",
    "newlib/libc/stdlib/assert.c",
    "newlib/libc/stdlib/assert_func.c",
    "newlib/libc/stdlib/assert_no_arg.c",
    "newlib/libc/stdlib/atexit.c",
    "newlib/libc/stdlib/atof.c",
    "newlib/libc/stdlib/atoff.c",
    "newlib/libc/stdlib/atoi.c",
    "newlib/libc/stdlib/atol.c",
    "newlib/libc/stdlib/atoll.c",
    "newlib/libc/stdlib/btowc.c",
    // "newlib/libc/stdlib/calloc.c",
    "newlib/libc/stdlib/cxa_atexit.c",
    "newlib/libc/stdlib/cxa_finalize.c",
    "newlib/libc/stdlib/div.c",
    "newlib/libc/stdlib/drand48.c",
    "newlib/libc/stdlib/dtoa.c",
    "newlib/libc/stdlib/ecvtbuf.c",
    "newlib/libc/stdlib/efgcvt.c",
    "newlib/libc/stdlib/environ.c",
    "newlib/libc/stdlib/eprintf.c",
    "newlib/libc/stdlib/erand48.c",
    "newlib/libc/stdlib/exit.c",
    "newlib/libc/stdlib/gdtoa-gethex.c",
    "newlib/libc/stdlib/gdtoa-hexnan.c",
    "newlib/libc/stdlib/getenv.c",
    "newlib/libc/stdlib/getenv_r.c",
    "newlib/libc/stdlib/getopt.c",
    "newlib/libc/stdlib/getsubopt.c",
    "newlib/libc/stdlib/imaxabs.c",
    "newlib/libc/stdlib/imaxdiv.c",
    "newlib/libc/stdlib/itoa.c",
    "newlib/libc/stdlib/jrand48.c",
    "newlib/libc/stdlib/l64a.c",
    "newlib/libc/stdlib/labs.c",
    "newlib/libc/stdlib/lcong48.c",
    "newlib/libc/stdlib/ldiv.c",
    "newlib/libc/stdlib/ldtoa.c",
    "newlib/libc/stdlib/llabs.c",
    "newlib/libc/stdlib/lldiv.c",
    "newlib/libc/stdlib/lrand48.c",
    "newlib/libc/stdlib/malloc-calloc.c",
    "newlib/libc/stdlib/malloc-cfree.c",
    "newlib/libc/stdlib/malloc-free.c",
    "newlib/libc/stdlib/malloc-mallinfo.c",
    "newlib/libc/stdlib/malloc-malloc.c",
    "newlib/libc/stdlib/malloc-malloc_stats.c",
    "newlib/libc/stdlib/malloc-malloc_usable_size.c",
    "newlib/libc/stdlib/malloc-mallopt.c",
    "newlib/libc/stdlib/malloc-memalign.c",
    "newlib/libc/stdlib/malloc-pvalloc.c",
    "newlib/libc/stdlib/malloc-realloc.c",
    "newlib/libc/stdlib/malloc-valloc.c",
    "newlib/libc/stdlib/mallocr.c",
    "newlib/libc/stdlib/mblen.c",
    "newlib/libc/stdlib/mbrlen.c",
    "newlib/libc/stdlib/mbrtowc.c",
    "newlib/libc/stdlib/mbsinit.c",
    "newlib/libc/stdlib/mbsnrtowcs.c",
    "newlib/libc/stdlib/mbsrtowcs.c",
    "newlib/libc/stdlib/mbstowcs.c",
    "newlib/libc/stdlib/mbtowc.c",
    "newlib/libc/stdlib/mbtowc_r.c",
    "newlib/libc/stdlib/mprec.c",
    "newlib/libc/stdlib/mrand48.c",
    "newlib/libc/stdlib/mstats.c",
    "newlib/libc/stdlib/nano-malloc-calloc.c",
    "newlib/libc/stdlib/nano-malloc-cfree.c",
    "newlib/libc/stdlib/nano-malloc-free.c",
    "newlib/libc/stdlib/nano-malloc-getpagesize.c",
    "newlib/libc/stdlib/nano-malloc-mallinfo.c",
    "newlib/libc/stdlib/nano-malloc-malloc.c",
    "newlib/libc/stdlib/nano-malloc-malloc_stats.c",
    "newlib/libc/stdlib/nano-malloc-malloc_usable_size.c",
    "newlib/libc/stdlib/nano-malloc-mallopt.c",
    "newlib/libc/stdlib/nano-malloc-memalign.c",
    "newlib/libc/stdlib/nano-malloc-posix_memalign.c",
    "newlib/libc/stdlib/nano-malloc-pvalloc.c",
    "newlib/libc/stdlib/nano-malloc-realloc.c",
    "newlib/libc/stdlib/nano-malloc-valloc.c",
    "newlib/libc/stdlib/nano-mallocr.c",
    "newlib/libc/stdlib/nrand48.c",
    "newlib/libc/stdlib/on_exit.c",
    "newlib/libc/stdlib/pico-atexit.c",
    "newlib/libc/stdlib/pico-cxa-atexit.c",
    "newlib/libc/stdlib/pico-exit.c",
    "newlib/libc/stdlib/pico-onexit.c",
    "newlib/libc/stdlib/putenv.c",
    "newlib/libc/stdlib/quick_exit.c",
    "newlib/libc/stdlib/rand.c",
    "newlib/libc/stdlib/rand48.c",
    "newlib/libc/stdlib/rand_r.c",
    "newlib/libc/stdlib/random.c",
    "newlib/libc/stdlib/reallocarray.c",
    "newlib/libc/stdlib/reallocf.c",
    "newlib/libc/stdlib/rpmatch.c",
    "newlib/libc/stdlib/sb_charsets.c",
    "newlib/libc/stdlib/seed48.c",
    "newlib/libc/stdlib/setenv.c",
    "newlib/libc/stdlib/srand.c",
    "newlib/libc/stdlib/srand48.c",
    "newlib/libc/stdlib/srandom.c",
    "newlib/libc/stdlib/strtod.c",
    "newlib/libc/stdlib/strtodg.c",
    "newlib/libc/stdlib/strtoimax.c",
    "newlib/libc/stdlib/strtol.c",
    "newlib/libc/stdlib/strtold.c",
    "newlib/libc/stdlib/strtoll.c",
    "newlib/libc/stdlib/strtorx.c",
    "newlib/libc/stdlib/strtoul.c",
    "newlib/libc/stdlib/strtoull.c",
    "newlib/libc/stdlib/strtoumax.c",
    "newlib/libc/stdlib/system.c",
    "newlib/libc/stdlib/utoa.c",
    "newlib/libc/stdlib/wcrtomb.c",
    "newlib/libc/stdlib/wcsnrtombs.c",
    "newlib/libc/stdlib/wcsrtombs.c",
    "newlib/libc/stdlib/wcstod.c",
    "newlib/libc/stdlib/wcstoimax.c",
    "newlib/libc/stdlib/wcstol.c",
    "newlib/libc/stdlib/wcstold.c",
    "newlib/libc/stdlib/wcstoll.c",
    "newlib/libc/stdlib/wcstoll_r.c",
    "newlib/libc/stdlib/wcstombs.c",
    "newlib/libc/stdlib/wcstoul.c",
    "newlib/libc/stdlib/wcstoull.c",
    "newlib/libc/stdlib/wcstoull_r.c",
    "newlib/libc/stdlib/wcstoumax.c",
    "newlib/libc/stdlib/wctob.c",
    "newlib/libc/stdlib/wctomb.c",
    "newlib/libc/stdlib/wctomb_r.c",
    "newlib/libc/string/bcmp.c",
    "newlib/libc/string/bcopy.c",
    "newlib/libc/string/bzero.c",
    "newlib/libc/string/explicit_bzero.c",
    "newlib/libc/string/ffsl.c",
    "newlib/libc/string/ffsll.c",
    "newlib/libc/string/fls.c",
    "newlib/libc/string/flsl.c",
    "newlib/libc/string/flsll.c",
    "newlib/libc/string/gnu_basename.c",
    "newlib/libc/string/index.c",
    "newlib/libc/string/memccpy.c",
    "newlib/libc/string/memchr.c",
    "newlib/libc/string/memcmp.c",
    "newlib/libc/string/memcpy.c",
    "newlib/libc/string/memmem.c",
    "newlib/libc/string/memmove.c",
    "newlib/libc/string/mempcpy.c",
    "newlib/libc/string/memrchr.c",
    "newlib/libc/string/memset.c",
    "newlib/libc/string/rawmemchr.c",
    "newlib/libc/string/rindex.c",
    "newlib/libc/string/stpcpy.c",
    "newlib/libc/string/stpncpy.c",
    "newlib/libc/string/strcasecmp.c",
    "newlib/libc/string/strcasecmp_l.c",
    "newlib/libc/string/strcasestr.c",
    "newlib/libc/string/strcat.c",
    "newlib/libc/string/strchr.c",
    "newlib/libc/string/strchrnul.c",
    "newlib/libc/string/strcmp.c",
    "newlib/libc/string/strcoll.c",
    "newlib/libc/string/strcoll_l.c",
    "newlib/libc/string/strcpy.c",
    "newlib/libc/string/strcspn.c",
    "newlib/libc/string/strdup.c",
    "newlib/libc/string/strerror.c",
    "newlib/libc/string/strerror_r.c",
    "newlib/libc/string/strlcat.c",
    "newlib/libc/string/strlcpy.c",
    "newlib/libc/string/strlen.c",
    "newlib/libc/string/strlwr.c",
    "newlib/libc/string/strncasecmp.c",
    "newlib/libc/string/strncasecmp_l.c",
    "newlib/libc/string/strncat.c",
    "newlib/libc/string/strncmp.c",
    "newlib/libc/string/strncpy.c",
    "newlib/libc/string/strndup.c",
    "newlib/libc/string/strnlen.c",
    "newlib/libc/string/strnstr.c",
    "newlib/libc/string/strpbrk.c",
    "newlib/libc/string/strrchr.c",
    "newlib/libc/string/strsep.c",
    "newlib/libc/string/strsignal.c",
    "newlib/libc/string/strspn.c",
    "newlib/libc/string/strstr.c",
    "newlib/libc/string/strtok.c",
    "newlib/libc/string/strtok_r.c",
    "newlib/libc/string/strupr.c",
    "newlib/libc/string/strverscmp.c",
    "newlib/libc/string/strxfrm.c",
    "newlib/libc/string/strxfrm_l.c",
    "newlib/libc/string/swab.c",
    "newlib/libc/string/timingsafe_bcmp.c",
    "newlib/libc/string/timingsafe_memcmp.c",
    "newlib/libc/string/u_strerr.c",
    "newlib/libc/string/wcpcpy.c",
    "newlib/libc/string/wcpncpy.c",
    "newlib/libc/string/wcscasecmp.c",
    "newlib/libc/string/wcscasecmp_l.c",
    "newlib/libc/string/wcscat.c",
    "newlib/libc/string/wcschr.c",
    "newlib/libc/string/wcscmp.c",
    "newlib/libc/string/wcscoll.c",
    "newlib/libc/string/wcscoll_l.c",
    "newlib/libc/string/wcscpy.c",
    "newlib/libc/string/wcscspn.c",
    "newlib/libc/string/wcsdup.c",
    "newlib/libc/string/wcslcat.c",
    "newlib/libc/string/wcslcpy.c",
    "newlib/libc/string/wcslen.c",
    "newlib/libc/string/wcsncasecmp.c",
    "newlib/libc/string/wcsncasecmp_l.c",
    "newlib/libc/string/wcsncat.c",
    "newlib/libc/string/wcsncmp.c",
    "newlib/libc/string/wcsncpy.c",
    "newlib/libc/string/wcsnlen.c",
    "newlib/libc/string/wcspbrk.c",
    "newlib/libc/string/wcsrchr.c",
    "newlib/libc/string/wcsspn.c",
    "newlib/libc/string/wcsstr.c",
    "newlib/libc/string/wcstok.c",
    "newlib/libc/string/wcswidth.c",
    "newlib/libc/string/wcsxfrm.c",
    "newlib/libc/string/wcsxfrm_l.c",
    "newlib/libc/string/wcwidth.c",
    "newlib/libc/string/wmemchr.c",
    "newlib/libc/string/wmemcmp.c",
    "newlib/libc/string/wmemcpy.c",
    "newlib/libc/string/wmemmove.c",
    "newlib/libc/string/wmempcpy.c",
    "newlib/libc/string/wmemset.c",
    "newlib/libc/string/xpg_strerror_r.c",
    // "newlib/libc/syscalls/sysgetentropy.c",
    "newlib/libc/time/asctime.c",
    "newlib/libc/time/asctime_r.c",
    "newlib/libc/time/clock.c",
    "newlib/libc/time/ctime.c",
    "newlib/libc/time/ctime_r.c",
    "newlib/libc/time/difftime.c",
    "newlib/libc/time/gettzinfo.c",
    "newlib/libc/time/gmtime.c",
    "newlib/libc/time/gmtime_r.c",
    "newlib/libc/time/lcltime.c",
    "newlib/libc/time/lcltime_buf.c",
    "newlib/libc/time/lcltime_r.c",
    "newlib/libc/time/mktime.c",
    "newlib/libc/time/month_lengths.c",
    "newlib/libc/time/strftime.c",
    "newlib/libc/time/strptime.c",
    "newlib/libc/time/time.c",
    "newlib/libc/time/tzcalc_limits.c",
    "newlib/libc/time/tzset.c",
    "newlib/libc/time/tzvars.c",
    "newlib/libc/time/wcsftime.c",
    // "newlib/libc/tinystdio/asprintf.c",
    // "newlib/libc/tinystdio/atod_engine.c",
    // "newlib/libc/tinystdio/atod_ryu.c",
    // "newlib/libc/tinystdio/atof_engine.c",
    // "newlib/libc/tinystdio/atof_ryu.c",
    // "newlib/libc/tinystdio/atold_engine.c",
    // "newlib/libc/tinystdio/bufio.c",
    // "newlib/libc/tinystdio/clearerr.c",
    // "newlib/libc/tinystdio/compare_exchange.c",
    // "newlib/libc/tinystdio/conv_flt.c",
    // "newlib/libc/tinystdio/dtoa_engine.c",
    // "newlib/libc/tinystdio/dtoa_ryu.c",
    // "newlib/libc/tinystdio/dtox_engine.c",
    // "newlib/libc/tinystdio/ecvt.c",
    // "newlib/libc/tinystdio/ecvt_r.c",
    // "newlib/libc/tinystdio/ecvtf.c",
    // "newlib/libc/tinystdio/ecvtf_r.c",
    // "newlib/libc/tinystdio/ecvtl.c",
    // "newlib/libc/tinystdio/ecvtl_r.c",
    // "newlib/libc/tinystdio/exchange.c",
    // "newlib/libc/tinystdio/fclose.c",
    // "newlib/libc/tinystdio/fcvt.c",
    // "newlib/libc/tinystdio/fcvt_r.c",
    // "newlib/libc/tinystdio/fcvtf.c",
    // "newlib/libc/tinystdio/fcvtf_r.c",
    // "newlib/libc/tinystdio/fcvtl.c",
    // "newlib/libc/tinystdio/fcvtl_r.c",
    // "newlib/libc/tinystdio/fdevopen.c",
    // "newlib/libc/tinystdio/fdopen.c",
    // "newlib/libc/tinystdio/feof.c",
    // "newlib/libc/tinystdio/ferror.c",
    // "newlib/libc/tinystdio/fflush.c",
    // "newlib/libc/tinystdio/fgetc.c",
    // "newlib/libc/tinystdio/fgets.c",
    // "newlib/libc/tinystdio/fgetwc.c",
    // "newlib/libc/tinystdio/fgetws.c",
    // "newlib/libc/tinystdio/fileno.c",
    // "newlib/libc/tinystdio/filestrget.c",
    // "newlib/libc/tinystdio/filestrput.c",
    // "newlib/libc/tinystdio/filestrputalloc.c",
    // "newlib/libc/tinystdio/filewstrget.c",
    // "newlib/libc/tinystdio/fmemopen.c",
    // "newlib/libc/tinystdio/fopen.c",
    // "newlib/libc/tinystdio/fprintf.c",
    // "newlib/libc/tinystdio/fputc.c",
    // "newlib/libc/tinystdio/fputs.c",
    // "newlib/libc/tinystdio/fputwc.c",
    // "newlib/libc/tinystdio/fputws.c",
    // "newlib/libc/tinystdio/fread.c",
    // "newlib/libc/tinystdio/freopen.c",
    // "newlib/libc/tinystdio/fscanf.c",
    // "newlib/libc/tinystdio/fseek.c",
    // "newlib/libc/tinystdio/fseeko.c",
    // "newlib/libc/tinystdio/ftell.c",
    // "newlib/libc/tinystdio/ftello.c",
    // "newlib/libc/tinystdio/ftoa_engine.c",
    // "newlib/libc/tinystdio/ftoa_ryu.c",
    // "newlib/libc/tinystdio/ftox_engine.c",
    // "newlib/libc/tinystdio/fwide.c",
    // "newlib/libc/tinystdio/fwprintf.c",
    // "newlib/libc/tinystdio/fwrite.c",
    // "newlib/libc/tinystdio/fwscanf.c",
    // "newlib/libc/tinystdio/gcvt.c",
    // "newlib/libc/tinystdio/gcvtf.c",
    // "newlib/libc/tinystdio/gcvtl.c",
    // "newlib/libc/tinystdio/getchar.c",
    // "newlib/libc/tinystdio/getdelim.c",
    // "newlib/libc/tinystdio/getline.c",
    // "newlib/libc/tinystdio/gets.c",
    // "newlib/libc/tinystdio/getwchar.c",
    // "newlib/libc/tinystdio/ldtoa_engine.c",
    // "newlib/libc/tinystdio/ldtox_engine.c",
    // "newlib/libc/tinystdio/matchcaseprefix.c",
    // "newlib/libc/tinystdio/mktemp.c",
    // "newlib/libc/tinystdio/perror.c",
    // "newlib/libc/tinystdio/posixiob_stderr.c",
    // "newlib/libc/tinystdio/posixiob_stdin.c",
    // "newlib/libc/tinystdio/posixiob_stdout.c",
    // "newlib/libc/tinystdio/printf.c",
    // "newlib/libc/tinystdio/putchar.c",
    // "newlib/libc/tinystdio/puts.c",
    // "newlib/libc/tinystdio/putwchar.c",
    // "newlib/libc/tinystdio/remove.c",
    // "newlib/libc/tinystdio/rewind.c",
    // "newlib/libc/tinystdio/ryu_divpow2.c",
    // "newlib/libc/tinystdio/ryu_log10.c",
    // "newlib/libc/tinystdio/ryu_log2pow5.c",
    // "newlib/libc/tinystdio/ryu_pow5bits.c",
    // "newlib/libc/tinystdio/ryu_table.c",
    // "newlib/libc/tinystdio/ryu_umul128.c",
    // "newlib/libc/tinystdio/scanf.c",
    // "newlib/libc/tinystdio/setbuf.c",
    // "newlib/libc/tinystdio/setbuffer.c",
    // "newlib/libc/tinystdio/setlinebuf.c",
    // "newlib/libc/tinystdio/setvbuf.c",
    // "newlib/libc/tinystdio/sflags.c",
    // "newlib/libc/tinystdio/snprintf.c",
    // "newlib/libc/tinystdio/snprintfd.c",
    // "newlib/libc/tinystdio/snprintff.c",
    // "newlib/libc/tinystdio/sprintf.c",
    // "newlib/libc/tinystdio/sprintfd.c",
    // "newlib/libc/tinystdio/sprintff.c",
    // "newlib/libc/tinystdio/sscanf.c",
    // "newlib/libc/tinystdio/strfromd.c",
    // "newlib/libc/tinystdio/strfromf.c",
    // "newlib/libc/tinystdio/strfroml.c",
    // "newlib/libc/tinystdio/strtod.c",
    // "newlib/libc/tinystdio/strtod_l.c",
    // "newlib/libc/tinystdio/strtof.c",
    // "newlib/libc/tinystdio/strtof_l.c",
    // "newlib/libc/tinystdio/strtoimax.c",
    // "newlib/libc/tinystdio/strtol.c",
    // "newlib/libc/tinystdio/strtol_l.c",
    // "newlib/libc/tinystdio/strtold.c",
    // "newlib/libc/tinystdio/strtold_l.c",
    // "newlib/libc/tinystdio/strtoll.c",
    // "newlib/libc/tinystdio/strtoll_l.c",
    // "newlib/libc/tinystdio/strtoul.c",
    // "newlib/libc/tinystdio/strtoul_l.c",
    // "newlib/libc/tinystdio/strtoull.c",
    // "newlib/libc/tinystdio/strtoull_l.c",
    // "newlib/libc/tinystdio/strtoumax.c",
    // "newlib/libc/tinystdio/swprintf.c",
    // "newlib/libc/tinystdio/swscanf.c",
    // "newlib/libc/tinystdio/tmpfile.c",
    // "newlib/libc/tinystdio/tmpnam.c",
    // "newlib/libc/tinystdio/ultoa_invert.c",
    // "newlib/libc/tinystdio/ungetc.c",
    // "newlib/libc/tinystdio/ungetwc.c",
    // "newlib/libc/tinystdio/vasprintf.c",
    // "newlib/libc/tinystdio/vffprintf.c",
    // "newlib/libc/tinystdio/vffscanf.c",
    // "newlib/libc/tinystdio/vfiprintf.c",
    // "newlib/libc/tinystdio/vfiscanf.c",
    // "newlib/libc/tinystdio/vflprintf.c",
    // "newlib/libc/tinystdio/vflscanf.c",
    // "newlib/libc/tinystdio/vfmprintf.c",
    // "newlib/libc/tinystdio/vfmscanf.c",
    // "newlib/libc/tinystdio/vfprintf.c",
    // "newlib/libc/tinystdio/vfscanf.c",
    // "newlib/libc/tinystdio/vfwprintf.c",
    // "newlib/libc/tinystdio/vfwscanf.c",
    // "newlib/libc/tinystdio/vprintf.c",
    // "newlib/libc/tinystdio/vscanf.c",
    // "newlib/libc/tinystdio/vsnprintf.c",
    // "newlib/libc/tinystdio/vsprintf.c",
    // "newlib/libc/tinystdio/vsscanf.c",
    // "newlib/libc/tinystdio/vswprintf.c",
    // "newlib/libc/tinystdio/vswscanf.c",
    // "newlib/libc/tinystdio/vwprintf.c",
    // "newlib/libc/tinystdio/vwscanf.c",
    // "newlib/libc/tinystdio/wprintf.c",
    // "newlib/libc/tinystdio/wscanf.c",
    // "newlib/libc/xdr/xdr.c",
    // "newlib/libc/xdr/xdr_array.c",
    // "newlib/libc/xdr/xdr_float.c",
    // "newlib/libc/xdr/xdr_float_vax.c",
    // "newlib/libc/xdr/xdr_mem.c",
    // "newlib/libc/xdr/xdr_private.c",
    // "newlib/libc/xdr/xdr_rec.c",
    // "newlib/libc/xdr/xdr_reference.c",
    // "newlib/libc/xdr/xdr_sizeof.c",
    // "newlib/libc/xdr/xdr_stdio.c",
};

const libm = &.{
    "newlib/libm/common/copysignl.c",
    "newlib/libm/common/cosf.c",
    "newlib/libm/common/exp.c",
    "newlib/libm/common/exp10l.c",
    "newlib/libm/common/exp2.c",
    "newlib/libm/common/exp_data.c",
    "newlib/libm/common/fabsl.c",
    "newlib/libm/common/frexpl.c",
    "newlib/libm/common/isgreater.c",
    // "newlib/libm/common/isinfl.c",
    // "newlib/libm/common/isnanl.c",
    "newlib/libm/common/log.c",
    "newlib/libm/common/log2.c",
    "newlib/libm/common/log2_data.c",
    "newlib/libm/common/log_data.c",
    "newlib/libm/common/math_denorm.c",
    "newlib/libm/common/math_denormf.c",
    "newlib/libm/common/math_denorml.c",
    "newlib/libm/common/math_err_check_oflow.c",
    "newlib/libm/common/math_err_check_uflow.c",
    "newlib/libm/common/math_err_divzero.c",
    "newlib/libm/common/math_err_invalid.c",
    "newlib/libm/common/math_err_may_uflow.c",
    "newlib/libm/common/math_err_oflow.c",
    "newlib/libm/common/math_err_uflow.c",
    "newlib/libm/common/math_err_with_errno.c",
    "newlib/libm/common/math_errf_check_oflowf.c",
    "newlib/libm/common/math_errf_check_uflowf.c",
    "newlib/libm/common/math_errf_divzerof.c",
    "newlib/libm/common/math_errf_invalidf.c",
    "newlib/libm/common/math_errf_may_uflowf.c",
    "newlib/libm/common/math_errf_oflowf.c",
    "newlib/libm/common/math_errf_uflowf.c",
    "newlib/libm/common/math_errf_with_errnof.c",
    "newlib/libm/common/math_inexact.c",
    "newlib/libm/common/math_inexactf.c",
    "newlib/libm/common/math_inexactl.c",
    "newlib/libm/common/nanl.c",
    "newlib/libm/common/nexttoward.c",
    "newlib/libm/common/nexttowardf.c",
    "newlib/libm/common/nexttowardl.c",
    "newlib/libm/common/pow.c",
    "newlib/libm/common/pow_log_data.c",
    "newlib/libm/common/s_cbrt.c",
    "newlib/libm/common/s_copysign.c",
    "newlib/libm/common/s_exp10.c",
    "newlib/libm/common/s_expm1.c",
    "newlib/libm/common/s_fdim.c",
    "newlib/libm/common/s_finite.c",
    "newlib/libm/common/s_fma.c",
    "newlib/libm/common/s_fmax.c",
    "newlib/libm/common/s_fmin.c",
    "newlib/libm/common/s_fpclassify.c",
    "newlib/libm/common/s_getpayload.c",
    "newlib/libm/common/s_ilogb.c",
    "newlib/libm/common/s_infinity.c",
    "newlib/libm/common/s_iseqsig.c",
    "newlib/libm/common/s_isinf.c",
    "newlib/libm/common/s_isinfd.c",
    "newlib/libm/common/s_isnan.c",
    "newlib/libm/common/s_isnand.c",
    "newlib/libm/common/s_issignaling.c",
    "newlib/libm/common/s_llrint.c",
    "newlib/libm/common/s_llround.c",
    "newlib/libm/common/s_log1p.c",
    "newlib/libm/common/s_log2.c",
    "newlib/libm/common/s_logb.c",
    "newlib/libm/common/s_lrint.c",
    "newlib/libm/common/s_lround.c",
    "newlib/libm/common/s_modf.c",
    "newlib/libm/common/s_nan.c",
    "newlib/libm/common/s_nearbyint.c",
    "newlib/libm/common/s_nextafter.c",
    "newlib/libm/common/s_pow10.c",
    "newlib/libm/common/s_remquo.c",
    "newlib/libm/common/s_rint.c",
    "newlib/libm/common/s_round.c",
    "newlib/libm/common/s_scalbln.c",
    "newlib/libm/common/s_scalbn.c",
    "newlib/libm/common/s_signbit.c",
    "newlib/libm/common/s_trunc.c",
    "newlib/libm/common/scalbnl.c",
    "newlib/libm/common/sf_cbrt.c",
    "newlib/libm/common/sf_copysign.c",
    "newlib/libm/common/sf_exp.c",
    "newlib/libm/common/sf_exp10.c",
    "newlib/libm/common/sf_exp2.c",
    "newlib/libm/common/sf_exp2_data.c",
    "newlib/libm/common/sf_expm1.c",
    "newlib/libm/common/sf_fdim.c",
    "newlib/libm/common/sf_finite.c",
    "newlib/libm/common/sf_fma.c",
    "newlib/libm/common/sf_fmax.c",
    "newlib/libm/common/sf_fmin.c",
    "newlib/libm/common/sf_fpclassify.c",
    "newlib/libm/common/sf_getpayload.c",
    "newlib/libm/common/sf_ilogb.c",
    "newlib/libm/common/sf_infinity.c",
    "newlib/libm/common/sf_iseqsig.c",
    "newlib/libm/common/sf_isinf.c",
    "newlib/libm/common/sf_isinff.c",
    "newlib/libm/common/sf_isnan.c",
    "newlib/libm/common/sf_isnanf.c",
    "newlib/libm/common/sf_issignaling.c",
    "newlib/libm/common/sf_llrint.c",
    "newlib/libm/common/sf_llround.c",
    "newlib/libm/common/sf_log.c",
    "newlib/libm/common/sf_log1p.c",
    "newlib/libm/common/sf_log2.c",
    "newlib/libm/common/sf_log2_data.c",
    "newlib/libm/common/sf_log_data.c",
    "newlib/libm/common/sf_logb.c",
    "newlib/libm/common/sf_lrint.c",
    "newlib/libm/common/sf_lround.c",
    "newlib/libm/common/sf_modf.c",
    "newlib/libm/common/sf_nan.c",
    "newlib/libm/common/sf_nearbyint.c",
    "newlib/libm/common/sf_nextafter.c",
    "newlib/libm/common/sf_pow.c",
    "newlib/libm/common/sf_pow10.c",
    "newlib/libm/common/sf_pow_log2_data.c",
    "newlib/libm/common/sf_remquo.c",
    "newlib/libm/common/sf_rint.c",
    "newlib/libm/common/sf_round.c",
    "newlib/libm/common/sf_scalbln.c",
    "newlib/libm/common/sf_scalbn.c",
    "newlib/libm/common/sf_trunc.c",
    "newlib/libm/common/signgam.c",
    "newlib/libm/common/sincosf.c",
    "newlib/libm/common/sincosf_data.c",
    "newlib/libm/common/sinf.c",
    "newlib/libm/common/sl_iseqsig.c",
    "newlib/libm/common/sl_issignaling.c",
    "newlib/libm/complex/cabs.c",
    "newlib/libm/complex/cabsf.c",
    "newlib/libm/complex/cabsl.c",
    "newlib/libm/complex/cacos.c",
    "newlib/libm/complex/cacosf.c",
    "newlib/libm/complex/cacosh.c",
    "newlib/libm/complex/cacoshf.c",
    "newlib/libm/complex/cacoshl.c",
    "newlib/libm/complex/cacosl.c",
    "newlib/libm/complex/carg.c",
    "newlib/libm/complex/cargf.c",
    "newlib/libm/complex/cargl.c",
    "newlib/libm/complex/casin.c",
    "newlib/libm/complex/casinf.c",
    "newlib/libm/complex/casinh.c",
    "newlib/libm/complex/casinhf.c",
    "newlib/libm/complex/casinhl.c",
    "newlib/libm/complex/casinl.c",
    "newlib/libm/complex/catan.c",
    "newlib/libm/complex/catanf.c",
    "newlib/libm/complex/catanh.c",
    "newlib/libm/complex/catanhf.c",
    "newlib/libm/complex/catanhl.c",
    "newlib/libm/complex/catanl.c",
    "newlib/libm/complex/ccos.c",
    "newlib/libm/complex/ccosf.c",
    "newlib/libm/complex/ccosh.c",
    "newlib/libm/complex/ccoshf.c",
    "newlib/libm/complex/ccoshl.c",
    "newlib/libm/complex/ccosl.c",
    "newlib/libm/complex/cephes_subr.c",
    "newlib/libm/complex/cephes_subrf.c",
    "newlib/libm/complex/cephes_subrl.c",
    "newlib/libm/complex/cexp.c",
    "newlib/libm/complex/cexpf.c",
    "newlib/libm/complex/cexpl.c",
    "newlib/libm/complex/cimag.c",
    "newlib/libm/complex/cimagf.c",
    "newlib/libm/complex/cimagl.c",
    "newlib/libm/complex/clog.c",
    "newlib/libm/complex/clog10.c",
    "newlib/libm/complex/clog10f.c",
    "newlib/libm/complex/clog10l.c",
    "newlib/libm/complex/clogf.c",
    "newlib/libm/complex/clogl.c",
    "newlib/libm/complex/conj.c",
    "newlib/libm/complex/conjf.c",
    "newlib/libm/complex/conjl.c",
    "newlib/libm/complex/cpow.c",
    "newlib/libm/complex/cpowf.c",
    "newlib/libm/complex/cpowl.c",
    "newlib/libm/complex/cproj.c",
    "newlib/libm/complex/cprojf.c",
    "newlib/libm/complex/cprojl.c",
    "newlib/libm/complex/creal.c",
    "newlib/libm/complex/crealf.c",
    "newlib/libm/complex/creall.c",
    "newlib/libm/complex/csin.c",
    "newlib/libm/complex/csinf.c",
    "newlib/libm/complex/csinh.c",
    "newlib/libm/complex/csinhf.c",
    "newlib/libm/complex/csinhl.c",
    "newlib/libm/complex/csinl.c",
    "newlib/libm/complex/csqrt.c",
    "newlib/libm/complex/csqrtf.c",
    "newlib/libm/complex/csqrtl.c",
    "newlib/libm/complex/ctan.c",
    "newlib/libm/complex/ctanf.c",
    "newlib/libm/complex/ctanh.c",
    "newlib/libm/complex/ctanhf.c",
    "newlib/libm/complex/ctanhl.c",
    "newlib/libm/complex/ctanl.c",
    "newlib/libm/fenv/fe_dfl_env.c",
    "newlib/libm/fenv/fegetmode.c",
    "newlib/libm/fenv/fenv.c",
    "newlib/libm/fenv/fesetmode.c",
    // "newlib/libm/ld/common/e_acosl.c",
    // "newlib/libm/ld/common/e_asinl.c",
    // "newlib/libm/ld/common/e_atan2l.c",
    // "newlib/libm/ld/common/e_lgammal.c",
    // "newlib/libm/ld/common/e_remainderl.c",
    // "newlib/libm/ld/common/e_sqrtl.c",
    // "newlib/libm/ld/common/k_rem_pio2.c",
    "newlib/libm/ld/common/polevll.c",
    // "newlib/libm/ld/common/s_atanl.c",
    // "newlib/libm/ld/common/s_cbrtl.c",
    // "newlib/libm/ld/common/s_cosl.c",
    // "newlib/libm/ld/common/s_fabsl.c",
    // "newlib/libm/ld/common/s_fdiml.c",
    // "newlib/libm/ld/common/s_finitel.c",
    // "newlib/libm/ld/common/s_fmaxl.c",
    // "newlib/libm/ld/common/s_fminl.c",
    // "newlib/libm/ld/common/s_frexpl.c",
    // "newlib/libm/ld/common/s_ilogbl.c",
    // "newlib/libm/ld/common/s_isinfl.c",
    // "newlib/libm/ld/common/s_isnanl.c",
    // "newlib/libm/ld/common/s_issignalingl.c",
    // "newlib/libm/ld/common/s_llrintl.c",
    // "newlib/libm/ld/common/s_llroundl.c",
    // "newlib/libm/ld/common/s_logbl.c",
    // "newlib/libm/ld/common/s_lrintl.c",
    // "newlib/libm/ld/common/s_lround.c",
    // "newlib/libm/ld/common/s_lroundl.c",
    // "newlib/libm/ld/common/s_rintl.c",
    // "newlib/libm/ld/common/s_roundl.c",
    // "newlib/libm/ld/common/s_scalbl.c",
    // "newlib/libm/ld/common/s_scalbln.c",
    // "newlib/libm/ld/common/s_scalbnl.c",
    // "newlib/libm/ld/common/s_significandl.c",
    // "newlib/libm/ld/common/s_sincosl.c",
    // "newlib/libm/ld/common/s_sinl.c",
    // "newlib/libm/ld/common/s_tanl.c",
    // "newlib/libm/ld/e_acoshl.c",
    "newlib/libm/ld/e_acosl.c",
    "newlib/libm/ld/e_asinl.c",
    "newlib/libm/ld/e_atan2l.c",
    "newlib/libm/ld/e_atanhl.c",
    "newlib/libm/ld/e_coshl.c",
    "newlib/libm/ld/e_expl.c",
    "newlib/libm/ld/e_fmodl.c",
    "newlib/libm/ld/e_hypotl.c",
    "newlib/libm/ld/e_lgammal.c",
    "newlib/libm/ld/e_lgammal_r.c",
    "newlib/libm/ld/e_log10l.c",
    "newlib/libm/ld/e_log2l.c",
    "newlib/libm/ld/e_logl.c",
    "newlib/libm/ld/e_powl.c",
    "newlib/libm/ld/e_remainderl.c",
    "newlib/libm/ld/e_sinhl.c",
    "newlib/libm/ld/e_sqrtl.c",
    "newlib/libm/ld/e_tgammal.c",
    "newlib/libm/ld/invtrig.c",
    // "newlib/libm/ld/k_cosl.c",
    // "newlib/libm/ld/k_rem_pio2.c",
    // "newlib/libm/ld/k_sinl.c",
    // "newlib/libm/ld/k_tanl.c",
    // "newlib/libm/ld/ld128/e_acoshl.c",
    // "newlib/libm/ld/ld128/e_atanhl.c",
    // "newlib/libm/ld/ld128/e_coshl.c",
    // "newlib/libm/ld/ld128/e_expl.c",
    // "newlib/libm/ld/ld128/e_fmodl.c",
    // "newlib/libm/ld/ld128/e_hypotl.c",
    // "newlib/libm/ld/ld128/e_lgammal_r.c",
    // "newlib/libm/ld/ld128/e_log10l.c",
    // "newlib/libm/ld/ld128/e_log2l.c",
    // "newlib/libm/ld/ld128/e_logl.c",
    // "newlib/libm/ld/ld128/e_powl.c",
    // "newlib/libm/ld/ld128/e_sinhl.c",
    // "newlib/libm/ld/ld128/e_tgammal.c",
    // "newlib/libm/ld/ld128/invtrig.c",
    // "newlib/libm/ld/ld128/k_cosl.c",
    // "newlib/libm/ld/ld128/k_sinl.c",
    // "newlib/libm/ld/ld128/k_tanl.c",
    // "newlib/libm/ld/ld128/s_asinhl.c",
    // "newlib/libm/ld/ld128/s_ceill.c",
    // "newlib/libm/ld/ld128/s_copysignl.c",
    // "newlib/libm/ld/ld128/s_erfl.c",
    // "newlib/libm/ld/ld128/s_exp2l.c",
    // "newlib/libm/ld/ld128/s_expm1l.c",
    // "newlib/libm/ld/ld128/s_floorl.c",
    // "newlib/libm/ld/ld128/s_fpclassifyl.c",
    // "newlib/libm/ld/ld128/s_getpayloadl.c",
    // "newlib/libm/ld/ld128/s_log1pl.c",
    // "newlib/libm/ld/ld128/s_modfl.c",
    // "newlib/libm/ld/ld128/s_nanl.c",
    // "newlib/libm/ld/ld128/s_nextafterl.c",
    // "newlib/libm/ld/ld128/s_nexttoward.c",
    // "newlib/libm/ld/ld128/s_nexttowardf.c",
    // "newlib/libm/ld/ld128/s_remquol.c",
    // "newlib/libm/ld/ld128/s_tanhl.c",
    // "newlib/libm/ld/ld128/s_truncl.c",
    // "newlib/libm/ld/ld80/e_acoshl.c",
    // "newlib/libm/ld/ld80/e_atanhl.c",
    // "newlib/libm/ld/ld80/e_coshl.c",
    // "newlib/libm/ld/ld80/e_expl.c",
    // "newlib/libm/ld/ld80/e_fmodl.c",
    // "newlib/libm/ld/ld80/e_hypotl.c",
    // "newlib/libm/ld/ld80/e_lgammal_r.c",
    // "newlib/libm/ld/ld80/e_log10l.c",
    // "newlib/libm/ld/ld80/e_log2l.c",
    // "newlib/libm/ld/ld80/e_logl.c",
    // "newlib/libm/ld/ld80/e_powl.c",
    // "newlib/libm/ld/ld80/e_sinhl.c",
    // "newlib/libm/ld/ld80/e_tgammal.c",
    // "newlib/libm/ld/ld80/invtrig.c",
    // "newlib/libm/ld/ld80/k_cosl.c",
    // "newlib/libm/ld/ld80/k_sinl.c",
    // "newlib/libm/ld/ld80/k_tanl.c",
    // "newlib/libm/ld/ld80/s_asinhl.c",
    // "newlib/libm/ld/ld80/s_ceill.c",
    // "newlib/libm/ld/ld80/s_copysignl.c",
    // "newlib/libm/ld/ld80/s_erfl.c",
    // "newlib/libm/ld/ld80/s_exp2l.c",
    // "newlib/libm/ld/ld80/s_expm1l.c",
    // "newlib/libm/ld/ld80/s_floorl.c",
    // "newlib/libm/ld/ld80/s_fpclassifyl.c",
    // "newlib/libm/ld/ld80/s_getpayloadl.c",
    // "newlib/libm/ld/ld80/s_log1pl.c",
    // "newlib/libm/ld/ld80/s_modfl.c",
    // "newlib/libm/ld/ld80/s_nanl.c",
    // "newlib/libm/ld/ld80/s_nextafterl.c",
    // "newlib/libm/ld/ld80/s_nexttoward.c",
    // "newlib/libm/ld/ld80/s_nexttowardf.c",
    // "newlib/libm/ld/ld80/s_remquol.c",
    // "newlib/libm/ld/ld80/s_tanhl.c",
    // "newlib/libm/ld/ld80/s_truncl.c",
    // "newlib/libm/ld/ldd/s_ceill.c",
    // "newlib/libm/ld/ldd/s_floorl.c",
    // "newlib/libm/ld/ldd/s_fpclassifyl.c",
    // "newlib/libm/ld/ldd/s_nanl.c",
    // "newlib/libm/ld/ldd/s_nearbyintl.c",
    // "newlib/libm/ld/ldd/s_truncl.c",
    "newlib/libm/ld/math_errl_check_oflowl.c",
    "newlib/libm/ld/math_errl_check_uflowl.c",
    "newlib/libm/ld/math_errl_divzerol.c",
    "newlib/libm/ld/math_errl_invalidl.c",
    "newlib/libm/ld/math_errl_oflowl.c",
    "newlib/libm/ld/math_errl_uflowl.c",
    "newlib/libm/ld/math_errl_with_errnol.c",
    "newlib/libm/ld/polevll.c",
    "newlib/libm/ld/s_asinhl.c",
    "newlib/libm/ld/s_atanl.c",
    "newlib/libm/ld/s_cbrtl.c",
    "newlib/libm/ld/s_ceill.c",
    "newlib/libm/ld/s_copysignl.c",
    "newlib/libm/ld/s_cosl.c",
    "newlib/libm/ld/s_erfl.c",
    "newlib/libm/ld/s_exp2l.c",
    "newlib/libm/ld/s_expm1l.c",
    "newlib/libm/ld/s_fabsl.c",
    "newlib/libm/ld/s_fdiml.c",
    "newlib/libm/ld/s_finitel.c",
    "newlib/libm/ld/s_floorl.c",
    "newlib/libm/ld/s_fmal.c",
    "newlib/libm/ld/s_fmaxl.c",
    "newlib/libm/ld/s_fminl.c",
    "newlib/libm/ld/s_fpclassifyl.c",
    "newlib/libm/ld/s_frexpl.c",
    "newlib/libm/ld/s_getpayloadl.c",
    "newlib/libm/ld/s_ilogbl.c",
    "newlib/libm/ld/s_isinfl.c",
    "newlib/libm/ld/s_isnanl.c",
    "newlib/libm/ld/s_issignalingl.c",
    "newlib/libm/ld/s_llrintl.c",
    "newlib/libm/ld/s_llroundl.c",
    "newlib/libm/ld/s_log1pl.c",
    "newlib/libm/ld/s_logbl.c",
    "newlib/libm/ld/s_lrintl.c",
    "newlib/libm/ld/s_lroundl.c",
    "newlib/libm/ld/s_modfl.c",
    "newlib/libm/ld/s_nanl.c",
    "newlib/libm/ld/s_nextafterl.c",
    "newlib/libm/ld/s_nexttoward.c",
    "newlib/libm/ld/s_nexttowardf.c",
    "newlib/libm/ld/s_remquol.c",
    "newlib/libm/ld/s_rintl.c",
    "newlib/libm/ld/s_roundl.c",
    "newlib/libm/ld/s_scalbl.c",
    "newlib/libm/ld/s_scalbln.c",
    "newlib/libm/ld/s_scalbnl.c",
    "newlib/libm/ld/s_significandl.c",
    "newlib/libm/ld/s_sincosl.c",
    "newlib/libm/ld/s_sinl.c",
    "newlib/libm/ld/s_tanhl.c",
    "newlib/libm/ld/s_tanl.c",
    "newlib/libm/ld/s_truncl.c",

    "newlib/libm/math/k_cos.c",
    "newlib/libm/math/k_rem_pio2.c",
    "newlib/libm/math/k_sin.c",
    "newlib/libm/math/k_tan.c",
    "newlib/libm/math/kf_cos.c",
    "newlib/libm/math/kf_rem_pio2.c",
    "newlib/libm/math/kf_sin.c",
    "newlib/libm/math/kf_tan.c",
    "newlib/libm/math/s_acos.c",
    "newlib/libm/math/s_acosh.c",
    "newlib/libm/math/s_asin.c",
    "newlib/libm/math/s_asinh.c",
    "newlib/libm/math/s_atan.c",
    "newlib/libm/math/s_atan2.c",
    "newlib/libm/math/s_atanh.c",
    "newlib/libm/math/s_ceil.c",
    "newlib/libm/math/s_cos.c",
    "newlib/libm/math/s_cosh.c",
    "newlib/libm/math/s_drem.c",
    "newlib/libm/math/s_erf.c",
    "newlib/libm/math/s_exp.c",
    "newlib/libm/math/s_exp2.c",
    "newlib/libm/math/s_fabs.c",
    "newlib/libm/math/s_floor.c",
    "newlib/libm/math/s_fmod.c",
    "newlib/libm/math/s_frexp.c",
    "newlib/libm/math/s_gamma.c",
    "newlib/libm/math/s_hypot.c",
    "newlib/libm/math/s_j0.c",
    "newlib/libm/math/s_j1.c",
    "newlib/libm/math/s_jn.c",
    "newlib/libm/math/s_lgamma.c",
    "newlib/libm/math/s_log.c",
    "newlib/libm/math/s_log10.c",
    "newlib/libm/math/s_pow.c",
    "newlib/libm/math/s_rem_pio2.c",
    "newlib/libm/math/s_remainder.c",
    "newlib/libm/math/s_scalb.c",
    "newlib/libm/math/s_signif.c",
    "newlib/libm/math/s_sin.c",
    "newlib/libm/math/s_sincos.c",
    "newlib/libm/math/s_sinh.c",
    "newlib/libm/math/s_sqrt.c",
    "newlib/libm/math/s_tan.c",
    "newlib/libm/math/s_tanh.c",
    "newlib/libm/math/s_tgamma.c",
    "newlib/libm/math/sf_acos.c",
    "newlib/libm/math/sf_acosh.c",
    "newlib/libm/math/sf_asin.c",
    "newlib/libm/math/sf_asinh.c",
    "newlib/libm/math/sf_atan.c",
    "newlib/libm/math/sf_atan2.c",
    "newlib/libm/math/sf_atanh.c",
    "newlib/libm/math/sf_ceil.c",
    "newlib/libm/math/sf_cos.c",
    "newlib/libm/math/sf_cosh.c",
    "newlib/libm/math/sf_drem.c",
    "newlib/libm/math/sf_erf.c",
    "newlib/libm/math/sf_exp.c",
    "newlib/libm/math/sf_exp2.c",
    "newlib/libm/math/sf_fabs.c",
    "newlib/libm/math/sf_floor.c",
    "newlib/libm/math/sf_fmod.c",
    "newlib/libm/math/sf_frexp.c",
    "newlib/libm/math/sf_gamma.c",
    "newlib/libm/math/sf_hypot.c",
    "newlib/libm/math/sf_j0.c",
    "newlib/libm/math/sf_j1.c",
    "newlib/libm/math/sf_jn.c",
    "newlib/libm/math/sf_lgamma.c",
    "newlib/libm/math/sf_log.c",
    "newlib/libm/math/sf_log10.c",
    "newlib/libm/math/sf_log2.c",
    "newlib/libm/math/sf_pow.c",
    "newlib/libm/math/sf_rem_pio2.c",
    "newlib/libm/math/sf_remainder.c",
    "newlib/libm/math/sf_scalb.c",
    "newlib/libm/math/sf_signif.c",
    "newlib/libm/math/sf_sin.c",
    "newlib/libm/math/sf_sincos.c",
    "newlib/libm/math/sf_sinh.c",
    "newlib/libm/math/sf_sqrt.c",
    "newlib/libm/math/sf_tan.c",
    "newlib/libm/math/sf_tanh.c",
    "newlib/libm/math/sf_tgamma.c",
    "newlib/libm/math/sl_hypot.c",
    "newlib/libm/math/sr_lgamma.c",
    "newlib/libm/math/srf_lgamma.c",
};
